### ISSUE TITLE
关于隔离级别的疑问

### ISSUE THREAD

**Issue by wuxudong** [codingapi/tx-lcn#100]
按我目前的理解， tx-lcn 主要是通过延迟关闭数据库连接的方式来达到 分布式事务。 虽然在最终提交前， 仍然需要占用数据库资源， 但由于解决了 应用程序的同步等待问题， 所以 整体效率比XA 会有很大的改进。

但我对tx-lcn 的隔离级别有些疑问。

假设有如下场景: 

各端的数据库为mysql， 本地事务的隔离级别都是 缺省的  Read-Repeatable

发起分布式事务 T1

发起方 S 执行本地事务A1， 修改对象 O 为 O'
参与方 P 执行本地事务B1， 修改对象 J 为 J'

在 T1 事务提交前，发起了 分布式 事务 T2

发起方 S 执行了本地事务 A2， 由于 T1 未提交(即A1， B1 未提交)  。 所以 A2 对 A1 的改动不可见。

此时 T1 事务提交。

同时 T2 发起方 调用 参与方 执行本地事务 B2， 修改对象 J， 由于 此时 T1 已提交 （即 A1, B1 已提交）。 B2 开始于 B1提交后， 因此对 B2 的改动是 可见的。

因此综上所述， 当分布式事务 T1 和 T2 有交叉时， T2 对 T1 的部分改动可见， 部分不可见。 

在隔离性上 弱化到了 不可重复读：在同一个事务中，对于同一份数据读取到的结果不一致。

是这样么？

**Comment by MikeLC7** [comment]
mysql默认的“REPEATABLE-READ”会不会出现这种情况：
1、发起方A远程调用B进行B的本地事务修改B1；
2、后续中A远程查询B的上次修改结果B1；
这个时候是可读还是不可读？
本机测试结果是不可读，造成相当严重的问题；
看LCN的日志，给步骤2中的查询添加事务之后应该是处于同一个事务中的，但是不知道为什么不可读？

**Comment by MrGui123** [comment]
@wuxudong 解决了应用程序的同步等待问题怎么理解

**Comment by wuxudong** [comment]
就是指 你的 应用程序 当成事务已经提交， 继续 执行 新的工作去了， 不会卡在那里。
