### ISSUE TITLE
事务补偿机制存在的问题

### ISSUE THREAD

**Issue by jaspercloud** [codingapi/tx-lcn#118]
阅读源码后，发现tx-lcn是通过重新调用事务方法实现事务补偿的。
如果是一个发帖子的业务，重新调用后返回的帖子id是新生成的，会导致事务补偿出问题。

**Comment by manorsuperman** [comment]
个人感觉LCN在补偿机制中存在很大的问题。它会重复去执行之前的整个步骤，而不是直接去补偿那些需要补偿的子事务。同时它删除补偿数据的依据 是 通过 重新执行这个接口返回的结果，而不是依赖那些还未完成的子事务的结果。
如果重新执行这个接口正常返回，那么会返回true,进而事务发起者会向tm发送补偿相应，例如：`{"p":{"d":"1"},"a":"c","k":"v17ZD1bO"}`，会导致tm删除补偿数据，实际上tm应该根据需要补偿的子事务是否执行成功来删除补偿数据。同时者也会引入一些问题，如果需要补偿的子事务有A,B, 但是只执行成功了A,那么B成功,那么也不应该删除补偿数据，应该继续重试B, 同时这些接口需要保证幂等性，如果没有这个保证，那么大多数逻辑都是有问题的。 同时需要锁机制来锁住那些需要正向补偿的接口的那些数据，不然可能会被其他进程更改这些数据（但是这可能会影响可用性）。虽然LCN名字中第一个L为lock,但是我没有看到任何关于锁这些数据的机制。还希望作者能够给出一些解释。也不知道我理解的对不对。
