### ISSUE TITLE
springboot 2.0 not support ？

### ISSUE THREAD

**Issue by venbill** [codingapi/tx-lcn#128]
can't start application

**Comment by kangjichang2009** [comment]
same problem！

**Comment by hoperunChen** [comment]
same problem

**Comment by war3sxkcs** [comment]
已经在springBoot2.0.6 & springCloud F 测试通过,但是 还是把作者的东西改动了一些才兼容测试通过的。应该没得多大的问题可以来用，但是要用到生产环境的话，可能要再调试下
