### ISSUE TITLE
熔断器只能用信号量吗？

### ISSUE THREAD

**Issue by aywangchen** [codingapi/tx-lcn#129]
@1991wangliang 4.0的视频中讲到，由于在Spring Cloud中通过feign的方式发起远程调用，需要从ThreadLocal中获取groupId等参数，熔断器如果采用多线程的方式会有问题。但是在4.1版本的demo中并没有找到将熔断器改为信号量的配置，想问一下在4.1版本中是否已经对熔断器采用多线程的方式进行了优化。
非常期待您的回复！

**Comment by jinkunaier** [comment]
@1991wangliang 同问，官网上说springcloud下在使用feign的hystrix时需要设置策略为信号量模式.，但是我改为THREAD方式也好使啊，另外代码中使用的是InheritableThreadLocal，应该是可以从子线程取到父线程设置变量的吧？

**Comment by aywangchen** [comment]
@jinkunaier 看过你两次回复后也有点明白了，目前为止LCN使用线程池隔离策略下还是有很大隐患的

**Comment by ujued** [comment]
4.x及以下、5.0.0.RELEASE和5.0.1.RELEASE必须用信号量模式，计划下个版本取消这个限制
