### ISSUE TITLE
访问springcloud-mybatis-demo测试报错

### ISSUE THREAD

**Issue by baixu19900206** [codingapi/tx-lcn#133]
我在本地启动tx-manager、springcloud-mybatis-demo1、springcloud-mybatis-demo2后，访问http://localhost:8081/demo/save
后，页面返回下面这个错误：请问有谁遇到过或怎么解决。

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Sep 03 18:06:42 CST 2018
There was an unexpected error (type=Internal Server Error, status=500).
status 500 reading Demo2Client#save(); content: {"timestamp":1535969201947,"status":500,"error":"Internal Server Error","exception":"java.lang.reflect.UndeclaredThrowableException","message":"No message available","path":"/demo/save"}

**Comment by WithLin** [comment]
我本地测试   没有问题
