### ISSUE TITLE
@TxTransaction(isStart=true)  屬性"isStart=true"可以不用設定

### ISSUE THREAD

**Issue by patofan** [codingapi/tx-lcn#134]
@TxTransaction(isStart=true) 
如果屬性"isStart=true"可以不用設定,而由系統自動判斷交易是否啟動.這樣程式會比較好寫.

**Comment by jinkunaier** [comment]
同问，事务发起方为什么一定要设置isStart=true，应该可以根据线程变量之类的判断出当前是否为事务的发起方？，这样设计的目的是什么？ 哪位大神知道，求解惑。

**Comment by WithLin** [comment]
谈谈我的想法吧，愚见: 我觉得isStart=true这样子更能让开发人员指导哪个是事务的发起方哪些是参与方。如果不要这个我觉得也是可以做，并不是通过线程变量之类的，可以判断当前的是否能拿到groupID,当前业务能劫持到groupId是参与方，不能劫持到也就是 空的。就是参与方。

**Comment by jinkunaier** [comment]
仔细想了一下，应该很难判断事务的发起方是哪个，根据当前是否能拿到groupId来判断会有问题，尤其是在 funA(){  funB();  funC(); } 这种情况下,funA与funB是同一个微服务实例下面的两个被@TxTransaction注解的方法,funC()其它微服务的，暂时不管它。根据目前的实现，此时在funA和funB的事务切面中都无法获取到groupId的  请@1991wangliang 大神解释一下设置isStart=true是基于什么样的考虑，不然用起来比较迷惑

**Comment by WithLin** [comment]
说是这么说 但是 A和B 不是发起方，但是D 或者 F 可以是啊。不通过groupid通过什么？ 再说A 和B获取不到不是正常吗？你没有生成Groupid。怎么获取？

**Comment by AngelSXD** [comment]
请问，我有个最基本的问题！
服务A调用服务B，A作为发起方，如果A中抛异常了，那么A、B都会回滚。
但是服务A调用服务B，A作为发起方，B作为参与方，我在B中发生异常了，只有B回滚了，A并不能回滚，请问怎么解决呢？

**Comment by TheCrazyRock** [comment]
对于@TxTransaction(isStart=true) 我也有些不明白的地方，望指导。
比如事务的嵌套场景。
作为一个发起方的服务funA()，如果被其他服务funX()调用后，调用者级服务funX()也做为发起方时，框架是如何处理的。示意如下：
funA(){funB();funC();}  此时funA设置了@TxTransaction(isStart=true) 
funX(){funA();} funX同样设置了@TxTransaction(isStart=true)
