### ISSUE TITLE
建议作者在重要地点处说明框架在应用Crash时会导致不一致的情况

### ISSUE THREAD

**Issue by skyesx** [codingapi/tx-lcn#137]
因个人之前有分布式事务相关经验，因此在浏览原理图时能发现在提交过程中（所有服务都回复可提交，然后发起方在协调者标志可提交后，部分服务提交成功，部分CRASH），发生应用crash的话，会导致数据不一致，出现某些服务可能提交，但某些没有提交的情况。

这是个很严重很根本的问题，若作者不提出来可能很多人都不清楚（至少我在看了几个重要的说明文档中都没看到），然后对此做了选型，可能并不符合其原有选型初衷

但若作者解决了上述问题，望不吝赐教！

**Comment by skyesx** [comment]
嗯，再看了一下，貌似作者这边使用了尝试正向补齐，若提交过程中部分成功部分失败，则继续重试调用执行未提交的那个服务。（以上未看代码，仅仅是猜测，若有不对，请指出）

这里有个问题感觉无法避免，就是CRASH后，服务的记录锁会释放调，例如要扣钱，原来是可以执行成功的因为之前余额足够，但后来由可能不够，因此该正向补做可能一直都不会成功

还望作者多做说明！

**Comment by wangzhengxi** [comment]
大佬，解决了没有

**Comment by wangzhengxi** [comment]
怎么解决
