### ISSUE TITLE
并发提交死锁

### ISSUE THREAD

**Issue by xmm4011** [codingapi/tx-lcn#145]
a  ->  b
a  ->  c

a事物发起方
b增加了@TxTransaction
c为三方网络请求，不存在事物、所以没有加@TxTransaction

同时发起两笔请求、参数一致、这个时候会出现mysql死锁

**Comment by AngelSXD** [comment]
请问，我有个最基本的问题！
服务A调用服务B，A作为发起方，如果A中抛异常了，那么A、B都会回滚。
但是服务A调用服务B，A作为发起方，B作为参与方，我在B中发生异常了，只有B回滚了，A并不能回滚，请问怎么解决呢？

**Comment by yizhishang** [comment]
可以回滚的
参考https://github.com/yizhishang/tx-lcn/tree/springcloud-2.0.4
