### ISSUE TITLE
LCN无法控制工作流的事务问题

### ISSUE THREAD

**Issue by chunericli** [codingapi/tx-lcn#147]
微服务A调用微服务B，微服务B调用工作流微服务，工作流微服务发起流程并操作数据库；
微服务A发生异常或者微服B发生异常后，工作流微服务的事务没回滚。

其余微服务场景没问题，设计工作流后就有问题，工作流这边是同步处理并返回结果；
猜想是工作流接管了Spring的事务导致的;

这问题怎么处理？

**Comment by AngelSXD** [comment]
请问，我有个最基本的问题！
服务A调用服务B，A作为发起方，如果A中抛异常了，那么A、B都会回滚。
但是服务A调用服务B，A作为发起方，B作为参与方，我在B中发生异常了，只有B回滚了，A并不能回滚，请问怎么解决呢？
