### ISSUE TITLE
分布式事务回滚是否真的有效？

### ISSUE THREAD

**Issue by AngelSXD** [codingapi/tx-lcn#148]
亲测：
情景1：
事务发起方A ，分别调用事务参与方B 、 C 。 A中抛出RuntimeException，则A，B，C均会回滚
情景2：
事务发起方A ，分别调用事务参与方B 、 C 。B或者C中任意一个抛出RuntimeException，则只有B或者C自己会回滚，发起方A和另一个参与方 都不会回滚！！！
情景3：
事务发起方A ，分别调用事务参与方B 、 C 。B或者C中任意一个先进行查询操作，再进行save操作，那么进行这种操作的服务，会卡在查询操作，不会走到save操作这一步，导致调用方A在超时时间后报错服务间响应超时！！！！

请问，大家有碰到这种问题么？
怎么解决的呢？？

注：
既然情景1已经可以实现回滚，那么
/**
     * 事务发起方
     *
     * 1.需要注解
     * @TxTransaction(isStart=true)     标明是事务发起方
     *
     * 2.需要注解
     * @Transactional       需要事务注解
     *
     * 3.需要TxManagerTxUrlServiceImpl 获取@Value("${tm.manager.url}")
     *
     */

/**
     * 事务参与方,被调用方
     *
     * 1.需要注解@TxTransaction 标明是事务参与方  或者 本service直接实现接口ITxTransaction
     *
     * 2.需要注解@Transactional
     *
     * 3.需要TxManagerTxUrlServiceImpl获取@Value("${tm.manager.url}")
     *
     */

都已经做了 ，所以不会是这些没有添加才导致的问题。

求大家帮忙啊

**Comment by war3sxkcs** [comment]
愚见：
老哥，我看到你出现在好几个issues里面了。。

情景1 ：如果A发生异常，已经就不会走到B和C了吧，那么这个时候跟BC都无关啊。
情景2 ：无论ABC哪个有问题了，大家都活不成。在这个Group组，大家都是同一条链上的蚂蚱，一个出问题全都得死。反正A不可能不会回滚。作者的视频里面有讲解。
情景3：不晓得，没测试过.....我是DeBug的时候超时过,真正操作的时候就远程Feign的时候有延迟可能会超时的吧

**Comment by war3sxkcs** [comment]
老哥你好，
你说到的情景2中，我只是在本地做过一个简单的demo,是没有问题的，我当时测试的环境是springCloud+springBoot 1.5.9 通过 Feign来调用测试的。我只是demo小测试，没有测试在像模像样的项目中。我们的下一个项目也正是要考虑使用LCN。LCN的作者说是可以这样的哈，老哥加油吧，我这段时间没有看了，在维护老项目






在 2018-12-03 10:24:03，"Jayezhuang" <notifications@github.com> 写道：


亲测：
情景1：
事务发起方A ，分别调用事务参与方B 、 C 。 A中抛出RuntimeException，则A，B，C均会回滚
情景2：
事务发起方A ，分别调用事务参与方B 、 C 。B或者C中任意一个抛出RuntimeException，则只有B或者C自己会回滚，发起方A和另一个参与方 都不会回滚！！！
情景3：
事务发起方A ，分别调用事务参与方B 、 C 。B或者C中任意一个先进行查询操作，再进行save操作，那么进行这种操作的服务，会卡在查询操作，不会走到save操作这一步，导致调用方A在超时时间后报错服务间响应超时！！！！

请问，大家有碰到这种问题么？
怎么解决的呢？？

注：
既然情景1已经可以实现回滚，那么
/**

事务发起方
1.需要注解
@TxTransaction(isStart=true) 标明是事务发起方
2.需要注解
@transactional 需要事务注解
3.需要TxManagerTxUrlServiceImpl 获取@value("${tm.manager.url}")

*/

/**

事务参与方,被调用方
1.需要注解@TxTransaction 标明是事务参与方 或者 本service直接实现接口ITxTransaction
2.需要注解@transactional
3.需要TxManagerTxUrlServiceImpl获取@value("${tm.manager.url}")

*/

都已经做了 ，所以不会是这些没有添加才导致的问题。

求大家帮忙啊

老哥，你的情景2 问题解决了吗，我也同样遇到没有回滚的情况，怀疑是不是哪边没有配置好?
在demo中，事务参与方 即被调用方，打印;
transaction is wait for TxManager notify, groupId : 3ZFB6YwU,在发起方回滚的时候，会打印:
lcn transaction over, res -> groupId:AVT5F0Hp and state is rollback;
但是在我的项目引用中，并没有打印相关信息

**Comment by AngelSXD** [comment]
不好意思，最近邮箱接到同志们的回复邮件通知。我在邮箱里进行了回复。但是这边还是统一回复一下比较好。



首先，感谢同志们的认真回复。也很抱歉，最后没有去统一给大家回复。其次，来说说我这里A->B  A->C  时候，B或者C发生异常，这一条链上都没有正常回滚的原因： 根源问题就是 我在整体的项目中，使用了异常统一拦截，在spring Cloud中，具体就是：

### ```
@ControllerAdvice
public class MyControllerAdvice {

    /**
     * 系统异常 拦截器
     * @param ex
     * @return
     */
    @ResponseBody
    @ExceptionHandler(value = Exception.class)
    public UniVerResponse<String> errorHandler(Exception ex) {
        ex.printStackTrace();
        return MyErrorResultBean.create(ex);
    }

    /**
     * 自定义异常  拦截器
     * @param ex
     * @return
     */
    @ResponseBody
    @ExceptionHandler(value = MyException.class)
    public MyErrorResultBean myErrorHandler(MyException ex) {
        ex.printStackTrace();
        return MyErrorResultBean.create(ex);
    }
}
```

这也就导致了在B中或者C中抛出的异常 被统一捕获，并未实际返回feign调用方，所以对于事务发起方，并未感知到出错了，最终才导致事务并未正常回滚！！


上面这个问题说完了，还有一个使用的情况如下：
 
A->B,A是事务发起方，B是事务参与方。B中不仅做了数据的新增或修改操作，还有查询操作。作为事务的参与方B，经过测试发现，即使是查询方法，也需要添加注解

`@Override
@Transactional
@TxTransaction
public Integral findByMember(String memberUid) {
    return integralDao.findByMemberUid(memberUid);
}`

========================================================
最后，非常感谢同志们的回复！！！
邮箱地址：sxd4business@qq.com
欢迎大家回复提问！！！
========================================================

[附上示例demo的GitHub地址:](https://github.com/AngelSXD/springcloud)

**Comment by yizhishang** [comment]
发起方和参与方的业务方法添加@Transactional注解和@TxTransaction注解
另外：发起方中的涉及分布式事务的方法要添加@TxTransaction(isStart = true)注解

**Comment by AngelSXD** [comment]
@sxyandapp bro,尝试去查找以下问题  LCN本身确实没有问题的！
另外，LCN5.0版本已经正式开源了  可以直接使用LCN5.0
