### ISSUE TITLE
如果txmanager设置了security，客户端报权限问题

### ISSUE THREAD

**Issue by crazyhuntsman** [codingapi/tx-lcn#15]
看了源码，最终调用HttpUtils里的方法，并未对Auth做处理。一般的服务布署后都要设置权限访问的。建议加上这一方面的处理。

当前解决方法：根据源码，提供自己实现TxManagerHttpRequestService接口，并注册至Spring容器

**Comment by 1991wangliang** [comment]
哦，其实TxManager是内部的调度中心，不对外提供访问的。
