### ISSUE TITLE
com.codingapi.tx.springcloud.listener.ServerListener 建议

### ISSUE THREAD

**Issue by wuzl807924995** [codingapi/tx-lcn#150]
这个类相当于客户端的启动类,现在项目不能支持springboot2.0就是因为 EmbeddedServletContainerInitializedEvent 这个事件在2.0中被删除了

我本地使用 直接改成了读取配置文件的端口
https://github.com/wuzl807924995/tx-lcn/blob/master/transaction-springcloud/src/main/java/com/codingapi/tx/springcloud/listener/ServerListener.java

比较建议的是把端口这个参数在启动的时候进行传递,或者抽取一个接口可以用不同的实现
比如1.x实现监听EmbeddedServletContainerInitializedEvent 
2.x 实现监听 ApplicationStartedEvent

另外2.0修改fegin 部分现在还没测试,不知道是否有其他改动

**Comment by yizhishang** [comment]
参考https://github.com/yizhishang/tx-lcn/tree/springcloud-2.0.4
已经支持feign，全面支持springcloud

**Comment by aohanhe** [comment]
我的工程使用了spring boot2.0遇到了找不到EmbeddedServletContainerInitializedEvent的问题，我看您的例子，tx-lcn是用的4.2.0的版本，我在maven仓库只能看到4.1.0的版本，这个怎么搞

**Comment by yizhishang** [comment]
若你引用的4.2.0是从我分享的那个是没有这个问题的
