### ISSUE TITLE
无法访问txmanage，已启动txmanage

### ISSUE THREAD

**Issue by forst2** [codingapi/tx-lcn#159]
txmanage已经启动了，但是还是无法访问，我想问下tm.manager.url的地址和端口到底是什么哪个地址和端口，是redis的地址和服务端口吗？

**Comment by Jayezhuang** [comment]
现在的服务端口应该是7000，看一下http://localhost:7000/index.html 是否能够访问？

**Comment by forst2** [comment]
这个和端口相关吗，我之前做的时候已经将properties中的server.port改为8899了
