### ISSUE TITLE
springCloud 多数据源的情况下 配置咨询

### ISSUE THREAD

**Issue by sniperZj** [codingapi/tx-lcn#16]
RT 多数据源的情况下 springcloud mybatis  demo 中的  LCNTransactionDataSource 配置需要改动吗

**Comment by 1991wangliang** [comment]
多数据源的情况下的思想是这样的。LCNTransactionDataSource是在最上层，然后下一层就是多数据源库。通过切面切换数据源即可。本身LCNTransactionDataSource不对数据源做控制的。为了简单的配置我们也打算提供一个多数据源版本的LCNTransactionDataSource的计划，不过用户也可以自行完成。

**Comment by sniperZj** [comment]
ok

**Comment by 1991wangliang** [comment]
https://github.com/codingapi/dubbo-lcn-demo/tree/master/dynamic-demo 等发布4.0.3以后就可以用了

**Comment by 1991wangliang** [comment]
这是一个多数据源切面的demo

**Comment by sniperZj** [comment]
👌

**Comment by wuganzhi** [comment]
> 
> 
> 这是一个多数据源切面的demo

目前没有看到多数据源的demo，请问最新版的在哪里配置
