### ISSUE TITLE
配置了Druid与Spring和Jdbc的关联监控，事务回滚无效

### ISSUE THREAD

**Issue by Daily1116** [codingapi/tx-lcn#160]
项目使用的是druid数据源，配置了spring.datasource.druid.aop-patterns，事务回滚无效，这个配置为什么会跟事务有关吗？

**Comment by charlesvhe** [comment]
我们也碰到这个问题，是因为配置监控aop后 DataSourceAspect 先与 TransactionAspect 执行，导致获取的connection不是被代理过的，回滚无效。
去掉这个监控，或者修改druid监控aop代码。

**Comment by Daily1116** [comment]
@charlesvhe  确实是这个问题，我debug源码看到了执行顺序，去掉配置监控后就好了，感谢
