### ISSUE TITLE
在一台机上启动多个dubbo 服务，不同的dubbo 端口号，tx-manager上连接数是正确的，但是在线模块不对数目不对

### ISSUE THREAD

**Issue by michaelshih** [codingapi/tx-lcn#166]
在一台机上启动多个dubbo 服务，不同的dubbo 端口号，tx-manager上连接数是正确的，但是在线模块不对数目不对

**Comment by guomaoyangeheh** [comment]
<dubbo:registry protocol="zookeeper" address="127.0.0.1:2181" port="20882" />  不同的模块port写成不同的，在线模块的数量就对了
