### ISSUE TITLE
对于@TxTransaction(isStart=true) 有些不明白的地方，望指导

### ISSUE THREAD

**Issue by TheCrazyRock** [codingapi/tx-lcn#168]
对于@TxTransaction(isStart=true) 我也有些不明白的地方，望指导。
比如事务的嵌套场景。
作为一个发起方的服务funA()，如果被其他服务funX()调用后，调用者级服务funX()也做为发起方时，框架是如何处理的？
示意如下：
funA(){funB();funC();} 此时funA设置了@TxTransaction(isStart=true)
funX(){funA();} funX同样设置了@TxTransaction(isStart=true)

**Comment by yizhishang** [comment]
被用作嵌套使用，可以正常使用，一条事务链，只有第一个@TxTransaction配置isStart=true有效

**Comment by TheCrazyRock** [comment]
明白了，感谢答复。
