### ISSUE TITLE
dubbo配置时，isStart = true,是否一定要配置在具有事物的service方法上，可以配置在controller层么

### ISSUE THREAD

**Issue by yishunli** [codingapi/tx-lcn#170]

**Comment by 1991wangliang** [comment]
尽量在业务层。

**Comment by 1991wangliang** [comment]
注解放在哪里都可以

**Comment by yishunli** [comment]
我测试了在controller层加的注解，但是没有实现事务回滚的，我实现的方式是这样的
controller里加入start=true,  在其中调用两个dubbo服务，在controller里抛出异常，看事务是否回滚，这样的测试是否可以验证分布式事务的正确性？
