### ISSUE TITLE
使用springcloud-2.0.4分支版本的lcn框架后，txmanager中没有事务补偿信息

### ISSUE THREAD

**Issue by aa007shuai** [codingapi/tx-lcn#172]
使用springcloud-2.0.4分支版本的lcn框架后，txmanager里面设置tm.compensate.auto=false。
服务运行中是有异常产生的，数据倒是正常回滚了，但是txmanager里面没有事务补偿的记录。
请问这是什么情况？

**Comment by aa007shuai** [comment]
> 被处理掉了

如何处理的？

**Comment by yizhishang** [comment]
这个时间间隔比较短
1. 添加事务，向redis记录数据
2. 回滚通知到的时候，回滚事务，然后删除redis数据

**Comment by aa007shuai** [comment]
> 这个时间间隔比较短
> 
> 1. 添加事务，向redis记录数据
> 2. 回滚通知到的时候，回滚事务，然后删除redis数据

抱歉这么久才回复，我记得原来的版本会保存那个需要补偿的记录的，如果回滚的时候直接删除了的话，我想手动补偿也补偿不了了是吧？
