### ISSUE TITLE
分布式集群问题

### ISSUE THREAD

**Issue by yushangcl** [codingapi/tx-lcn#180]
![image](https://user-images.githubusercontent.com/12591426/50681229-ae9fb200-1045-11e9-9dd9-ddd5fe3d2ff7.png)

----------案例---------- 场景： 一个微服务A , 部署了两个节点 A1 和 A2 ，当我的事务组发起方是 B 时，在同一业务中，多次调用到A服务的数据。 问题： 多次调用A时，发现，有可能到A1 有可能到A2，同一分布式事务中，如果通过A1插入了数据（假提交），又调用A2来获取---会获取不到

LcnLoadBalancerRule.proxy()方法中getServer 获取 oldServer，然后继续return server，不能实现同一事务调用在同一服务上

**Comment by 1991wangliang** [comment]
这个问题，若存在是bug.建议尝试一下5.0版本。

**Comment by 1991wangliang** [comment]
对的
