### ISSUE TITLE
关于tx自身的分布式集群问题

### ISSUE THREAD

**Issue by eryajf** [codingapi/tx-lcn#184]
目前tx应用属于单台，希望部署为集群架构，参考了文档中的说明，部署两台tx，前端通过nginx代理，然后应用写成nginx的地址进行注册，这个时候发现，由于nginx的轮询机制，在应用启动的时候，会只注册到某一台tx中，这样一来，高可用好像也就没有意义了，不知是否还有更好的建议

**Comment by meetzy** [comment]
目前5.0版本是客户端配置多Manager
