### ISSUE TITLE
spring 本身的事务传播级别问题

### ISSUE THREAD

**Issue by mostermsater** [codingapi/tx-lcn#188]
发起事务的方法调用d,e 两个client的保存方法，同时调用一个自身的其他的保存方法，这个自身的保存方法想做到无论d,e报不报错都要存到数据库，在分布式事务的情况下，这个方法也会回滚，spring本身的事务传播无效了就

**Comment by mostermsater** [comment]
还有，如果循环调用client的方法，第一次会回滚，往后的都不会回滚

**Comment by ujued** [comment]
1、TXLCN-5.0 新加了分布式事务传播行为，但依然不支持你说的这种情况（很少见吧），仅支持【REQUIRED】【SUPPORTS】
2、TXLCN-5.0 此问题有所改善
