### ISSUE TITLE
集群模式下负载均衡的疑问

### ISSUE THREAD

**Issue by sunnyWu1104** [codingapi/tx-lcn#189]
`
public Server proxy(List<Server> servers,Server server){

		TxTransactionLocal txTransactionLocal = TxTransactionLocal.current();
		if(txTransactionLocal==null){
			return server;
		}

		try{
			logger.debug("LCNBalanceProxy - > start");

			String groupId = txTransactionLocal.getGroupId();

			//取出组件的appName
			String appName = server.getMetaInfo().getAppName();

			String key = MD5Util.md5((groupId + "_" + appName).getBytes());

			//如果只有一个可调用模块，则用当前的，且需要将数据记录到redis中
			if(servers.size() == 1){
				putServer(key, txTransactionLocal, server);
				logger.debug("LCNBalanceProxy -> only one server available");
				return server;
			}

			Server oldServer =getServer(txTransactionLocal,servers,key);
			if(oldServer != null){
				logger.debug("LCNBalanceProxy - > load old server ");
				return server;
			}

			putServer(key, txTransactionLocal, server);
			logger.debug("LCNBalanceProxy - > load new server ");

			return server;
		}finally {
			logger.debug("LCNBalanceProxy - > end");
		}
	}
`
问题1:既然使用LB算法选择当前的服务，为什么还要查询oldServer？
问题2:putServer方法中txTransactionLocal.putLoadBalance(key,md5);是否会造成内存溢出？

上述问题有可能也是我管中窥豹!!

**Comment by situying** [comment]
`
Server oldServer =getServer(txTransactionLocal,servers,key);
if(oldServer != null){
    logger.debug("LCNBalanceProxy - > load old server ");
    return server;
}
`
这里有bug吧，既然oldServer不空，为什么还返回server而不是oldServer，这个判断的意思是什么？

**Comment by 1991wangliang** [comment]
问题已修复
