### ISSUE TITLE
无spring下是否可以使用

### ISSUE THREAD

**Issue by pkanyue** [codingapi/tx-lcn#19]
请问如何在不使用spring的情况下使用tx-lcn，有参考demo吗，tx-manager是否支持使用别的注册中心，比如consul/zookeeper？

**Comment by 1991wangliang** [comment]
lcn是必修依赖spring的。tx-manager目前只是基于springcloud机制上的eureka的依赖，理论上可以修改为其他的依赖。

**Comment by pkanyue** [comment]
谢谢回答，目前我没有寻找到非spring环境下，有效的分布式事务的解决方案，但想使用tx-lcn，请问我是否可以fork client源码，将依赖 spring 的部分修改为非spring依赖实现，然后配合 tx-manager 使用 ？

**Comment by 1991wangliang** [comment]
可以啊 ，LCN是开源
