### ISSUE TITLE
tx-logger 日志连接数量过多

### ISSUE THREAD

**Issue by YangAnLin** [codingapi/tx-lcn#192]

**Comment by YangAnLin** [comment]
用的5.0项目里的 example  spring-demo 的项目,e项目,启动的时候提示
![image](https://user-images.githubusercontent.com/30170561/51068753-a0f9b600-165d-11e9-8ee0-b053e3305efb.png)

**Comment by ujued** [comment]
`spring.datasource.hikari.maximum-pool-size=1000`。当时为了压测才搞得这么大，你可以把它调小, MySQL服务默认似乎是100个。日志过多什么意思？

**Comment by YangAnLin** [comment]
使用mysql 默认的连接数,5.0的demo的配置也都是默认的,除了数据库url之类的配置,同时启动两个e 服务,第二个启动的时候,就会报  连接过多的错误
