### ISSUE TITLE
5.0.0.RC1 启动与 spring-retry 冲突。

### ISSUE THREAD

**Issue by duanyingchao** [codingapi/tx-lcn#193]
**Describe the bug**
试用 5.0.0.RC1 过程中 由于项目集成 spring-boot-starter-amqp 项目启动 报错：

01-16 12:06:35 [main] | ERROR | org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter   42 - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in com.codingapi.tx.client.springcloud.spi.sleuth.ribbon.customizer.RibbonFirstRestTemplateCustomizer required a bean of type 'org.springframework.cloud.client.loadbalancer.LoadBalancerInterceptor' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'ribbonInterceptor' in 'LoadBalancerAutoConfiguration.LoadBalancerInterceptorConfig' not loaded because @ConditionalOnMissingClass found unwanted class 'org.springframework.retry.support.RetryTemplate'

Action:

Consider revisiting the entries above or defining a bean of type 'org.springframework.cloud.client.loadbalancer.LoadBalancerInterceptor' in your configuration.

![image](https://user-images.githubusercontent.com/15629379/51096349-d980c780-17f6-11e9-9b44-f4ee555273c9.png)

**Comment by 1991wangliang** [comment]
你可以尝试这样修改一下，我们后面会修复
```
package com.codingapi.tx.client.springcloud.spi.sleuth.ribbon.customizer;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cloud.client.loadbalancer.LoadBalancerInterceptor;
import org.springframework.cloud.client.loadbalancer.RestTemplateCustomizer;
import org.springframework.cloud.client.loadbalancer.RetryLoadBalancerInterceptor;
import org.springframework.http.client.ClientHttpRequestInterceptor;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestTemplate;

import java.util.ArrayList;
import java.util.List;

/**
 * Description: set loadBalancerInterceptor to first.
 * Company: CodingApi
 * Date: 2018/12/18
 *
 * @author codingapi
 */
@Component
public class RibbonFirstRestTemplateCustomizer implements RestTemplateCustomizer {


    @Autowired(required = false)
    private LoadBalancerInterceptor loadBalancerInterceptor;

    @Autowired(required = false)
    private RetryLoadBalancerInterceptor retryLoadBalancerInterceptor;


    @Override
    public void customize(RestTemplate restTemplate) {
        List<ClientHttpRequestInterceptor> list = new ArrayList<>(restTemplate.getInterceptors());
        if(loadBalancerInterceptor!=null) {
            list.add(0, loadBalancerInterceptor);
        }
        if(retryLoadBalancerInterceptor!=null){
            list.add(0, retryLoadBalancerInterceptor);
        }
        restTemplate.setInterceptors(list);
    }

}

```

**Comment by duanyingchao** [comment]
可否这样修改，将LoadBalancerInterceptor 替换为ClientHttpRequestInterceptor
`package com.codingapi.tx.client.springcloud.spi.sleuth.ribbon.customizer;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cloud.client.loadbalancer.LoadBalancerInterceptor;
import org.springframework.cloud.client.loadbalancer.RestTemplateCustomizer;
import org.springframework.http.client.ClientHttpRequestInterceptor;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestTemplate;

import java.util.ArrayList;
import java.util.List;

/**
 * Description: set loadBalancerInterceptor to first.
 * Company: CodingApi
 * Date: 2018/12/18
 *
 * @author codingapi
 */
@Component
public class RibbonFirstRestTemplateCustomizer implements RestTemplateCustomizer {


    private ClientHttpRequestInterceptor loadBalancerInterceptor;

    @Autowired
    public RibbonFirstRestTemplateCustomizer(ClientHttpRequestInterceptor loadBalancerInterceptor) {
        this.loadBalancerInterceptor = loadBalancerInterceptor;
    }

    @Override
    public void customize(RestTemplate restTemplate) {
        List<ClientHttpRequestInterceptor> list = new ArrayList<>(restTemplate.getInterceptors());
        list.add(0,loadBalancerInterceptor);
        restTemplate.setInterceptors(list);
    }

}`


@1991wangliang

**Comment by 1991wangliang** [comment]
OK，这样也可以。
