### ISSUE TITLE
TxTransactionLocal里头，使用threadlocal能保证高并发的性能和安全吗

### ISSUE THREAD

**Issue by yizhishang** [codingapi/tx-lcn#194]
1. 类似TxTransactionLocal.makeNeverAppeared()这种操作会否在意外情况下，清空所有的事务信息
2. 现有的框架还是单线程控制事务，同一时间只能期望处理一个事务组；
3. 控制事务的粒度还是比较大能够通过ConcurrentHashMap来缩小粒度，以groupId为key值存储TxTransactionLocal信息，可以保证事务传播过程中的其他事务信息的安全

**Comment by yizhishang** [comment]
我做了个并发测试，如下：
用力数量	耗时(ms)	平均耗时(ms/个)
   30		8722			290
  100	29410			294
  200	47842			239

基本上，总耗时和用例数量成正比

**Comment by ujued** [comment]
1.意外情况是指？
2.SpringMVC，线程执行接口方法时，会且只会执行这一个方法到执行完毕。原理上，LCN切入了方法，给业务增加了协调代码，这里单线程是SpringMVC设定好的。
3.groupId只在业务代码执行前后有用，这时把其相关信息绑定到业务线程本地比较合理，没必要再用其它的方式。

**Comment by 1991wangliang** [comment]
请求每次处理完以后线程会在清理数据的。

**Comment by JasonShow** [comment]
每次方法执行完会在handler拦截器清除本地线程变量里面存的东西,不会存在ThreadLocal内存泄露.
