### ISSUE TITLE
tx-manager库的t_logger表app_name永远都是“tx-manager”

### ISSUE THREAD

**Issue by yizhishang** [codingapi/tx-lcn#198]
是否应该展示的是各个参与事务参与方，而非tx-manager协调器

**Comment by lynk-coder** [comment]
建议增加端口
![22222](https://user-images.githubusercontent.com/23651124/51181592-85650880-1906-11e9-9c23-2e29a31a8c6a.png)

**Comment by lynk-coder** [comment]
建议 新增参与方字段 clients_set   记录执行参与者

**Comment by 1991wangliang** [comment]
已经考虑优化了。
