### ISSUE TITLE
 SocketManager中appName全局变量的数据只会增加不会删除

### ISSUE THREAD

**Issue by deanjoson** [codingapi/tx-lcn#199]
在com.codingapi.txlcn.spi.message.netty.SocketManager中有一个全局变量appName，用于记录所有在线模块的客户端名称，该全局变量是一个ConcurrentHashMap，系统提供了一个【public void bindModuleName(String remoteKey, String moduleName)】的方法用于添加appName的map数据，同时提供了一个【public void removeChannel(Channel channel)】的方法用于对失效的客户端模块进行删除。但是添加方法和删除方法使用key值不统一，导致只能添加无法删除。长此以往，如果客户端数量较多且进行重复的启动会导致该全局变量数据量庞大，最终导致内存溢出的问题出现。
```java
 public void removeChannel(Channel channel) {
        channels.remove(channel);
        try {
            executorService.schedule(() -> {
                String key = channel.toString();
                appNames.remove(key);
            }, attrDelayTime, TimeUnit.SECONDS);
        } catch (RejectedExecutionException ignored) {
            // down server.
        }
    }
```
```java
   public void bindModuleName(String remoteKey, String moduleName) {
        appNames.put(remoteKey, moduleName);
    }
```

绑定客户端名称DEBUG截图:
![绑定客户端名称DEBUG截图t](http://public-coolwang.oss-cn-hongkong.aliyuncs.com/appName_add.png)

移除客户端名称DEBUG截图:
![移除客户端名称DEBUG截图t](http://public-coolwang.oss-cn-hongkong.aliyuncs.com/appName_remove.png)

**Comment by meetzy** [comment]
我看了下 忘记调用remoteAddress方法了 感谢
