### ISSUE TITLE
关于使用H2生成的数据库文件 *.mv.db的bug

### ISSUE THREAD

**Issue by lynk-coder** [codingapi/tx-lcn#200]
我发现一个问题，关于生成的*.mv.db临时数据库文件，使用的是application name，导致同名的application name微服务无法启动。
![qq 20190115185018](https://user-images.githubusercontent.com/23651124/51175894-80985880-18f6-11e9-966d-b3dec998249a.png)
![qq 20190115185032](https://user-images.githubusercontent.com/23651124/51175897-82fab280-18f6-11e9-8639-828f49c0f977.png)

**Comment by lynk-coder** [comment]
![11111](https://user-images.githubusercontent.com/23651124/51177560-e5ee4880-18fa-11e9-9e62-56ed92f14b3b.png)

**Comment by meetzy** [comment]
此问题已经修改  感谢！

**Comment by lynk-coder** [comment]
> 此问题已经修改 感谢！

客气，你们辛苦了。加油！
