### ISSUE TITLE
lcn5.0.0beat  springboot2.0降到1.5 出现问题，麻烦分析一下

### ISSUE THREAD

**Issue by yx726843014** [codingapi/tx-lcn#203]
springboot下降到1.5的时候，服务端manager没有报错，但是client端进行请求的时候sleuth报错，错误信息【java.lang.RuntimeException: sleuth pass error.】；
后来试着把sleuth升级到2.0左右，启动就报错无法找到webFilter类，这个类是spring-web5.0才有的，也就是springboot2.0以上的版本。是不是不能降级处理。

**Comment by qxf567** [comment]
使用springboot1.X的版本，sleuth通信上有问题，所以会出各种问题。

**Comment by 1991wangliang** [comment]
5.0.1.RELEASE版本支持。
spring boot 1.5.x demo:
https://github.com/codingapi/txlcn-demo/tree/1.5.boot
