### ISSUE TITLE
重要：#关于调用者捕获异常不影响事务回滚判断，并只基于service的事务异常进行全局回滚的建议#

### ISSUE THREAD

**Issue by lynk-coder** [codingapi/tx-lcn#204]
现如今TXLCN对事务的回滚判断主要基于微服务调用过程中（A->B），被调用的微服务是否抛出异常来进行全局回滚的。
如果在B中已经自行捕获了异常，那么将影响到全局事务的判断，导致最终事务会被提交。
但是，由于大多数企业项目开发的习惯，对于捕获后的异常会返回相应的错误代码（error_code）之类的，目前TXLCN的捕获异常的方式会增加一些相应的开发成本和占用相应的系统资源（如：开发一套route服务，或对全局异常进行二次编写已达到异常返回能附带错误编码）

个人建议将事务级别定义在service层，调用者（如Controller）捕获异常后将不影响整体的回滚。

将sleuth（group）利用起来，仅仅只是建议哈。

具体如图下：

![111](https://user-images.githubusercontent.com/23651124/51250584-c5dd8880-19d1-11e9-8624-b1b7dfbab649.png)

![2222](https://user-images.githubusercontent.com/23651124/51250586-c83fe280-19d1-11e9-887b-e6f9f8c2c7b9.png)

![3333](https://user-images.githubusercontent.com/23651124/51250598-d2fa7780-19d1-11e9-8108-191721ff2d63.png)

**Comment by szlzhm** [comment]
在发起方的service中判断参与方返回的错误码，再根据错误码决定抛出异常，处罚发起者的RuntimeException是否解决问题？

**Comment by lynk-coder** [comment]
> 在发起方的service中判断参与方返回的错误码，再根据错误码决定抛出异常，处罚发起者的RuntimeException是否解决问题？

关于这个方案我之前也是如此试用的，但是对于强一致的业务，开发成本相对比较高，要层层判断。
大多数微服务开发是多个人协同的，所以对开发协调要求十分的高。
