### ISSUE TITLE
建议将SQL语句从代码里分离出来

### ISSUE THREAD

**Issue by yuan-dong-li** [codingapi/tx-lcn#207]
目前SQL语句基本都写死在代码里，无论是client或者tx-manager实际上无法用于其他数据库。是否有计划支持其他数据库比如PostgreSQL之类？

**Comment by 1991wangliang** [comment]
嗯 这个问题我们会考虑的，已经在分离了

**Comment by 1991wangliang** [comment]
5.0.2 版本采用了jpa模式
