### ISSUE TITLE
点击补偿按钮报错，开启自动补偿也会报错，版本4.0.3快照

### ISSUE THREAD

**Issue by wuzunqian** [codingapi/tx-lcn#21]
补偿本地记录：data1=C5IBMmNvbS55eXRjbG91ZC5kdHMuc2FtcGxlLmNvbnN1bWVyLmltcGwuQ29uc3VtZXJJbXBsDBIGaW5zZXJ0G3oQamF2YS5sYW5nLk9iamVjdBgDEAEL+gc+bmMuamRiYy5mcmFtZXdvcmsudHJhbnNhY3Rpb24uRGVmYXVsdFl5dFNlcnZpY2VEYXRhU291cmNlUGFyYW0MHCN6D2phdmEubGFuZy5DbGFzcxgDEAELkgE4bmMuamRiYy5mcmFtZXdvcmsudHJhbnNhY3Rpb24uSVl5dFNlcnZpY2VEYXRhU291cmNlUGFyYW0MC5IBEGphdmEubGFuZy5TdHJpbmcMC5IBEGphdmEubGFuZy5TdHJpbmcMJCrIAXB1YmxpYyBqYXZhLmxhbmcuU3RyaW5nIGNvbS55eXRjbG91ZC5kdHMuc2FtcGxlLmNvbnN1bWVyLmltcGwuQ29uc3VtZXJJbXBsLmluc2VydChuYy5qZGJjLmZyYW1ld29yay50cmFuc2FjdGlvbi5JWXl0U2VydmljZURhdGFTb3VyY2VQYXJhbSxqYXZhLmxhbmcuU3RyaW5nLGphdmEubGFuZy5TdHJpbmcpIHRocm93cyBqYXZhLmxhbmcuRXhjZXB0aW9u
redis上保存的数据:
data2=C5IBMmNvbS55eXRjbG91ZC5kdHMuc2FtcGxlLmNvbnN1bWVyLmltcGwuQ29uc3VtZXJJbXBsDBIGaW5zZXJ0G3oQamF2YS5sYW5nLk9iamVjdBgDEAEL gc bmMuamRiYy5mcmFtZXdvcmsudHJhbnNhY3Rpb24uRGVmYXVsdFl5dFNlcnZpY2VEYXRhU291cmNlUGFyYW0MHCN6D2phdmEubGFuZy5DbGFzcxgDEAELkgE4bmMuamRiYy5mcmFtZXdvcmsudHJhbnNhY3Rpb24uSVl5dFNlcnZpY2VEYXRhU291cmNlUGFyYW0MC5IBEGphdmEubGFuZy5TdHJpbmcMC5IBEGphdmEubGFuZy5TdHJpbmcMJCrIAXB1YmxpYyBqYXZhLmxhbmcuU3RyaW5nIGNvbS55eXRjbG91ZC5kdHMuc2FtcGxlLmNvbnN1bWVyLmltcGwuQ29uc3VtZXJJbXBsLmluc2VydChuYy5qZGJjLmZyYW1ld29yay50cmFuc2FjdGlvbi5JWXl0U2VydmljZURhdGFTb3VyY2VQYXJhbSxqYXZhLmxhbmcuU3RyaW5nLGphdmEubGFuZy5TdHJpbmcpIHRocm93cyBqYXZhLmxhbmcuRXhjZXB0aW9u
点击补偿报错
Caused by: com.dyuproject.protostuff.ProtostuffException: Corrupt input.  Unknown field number: 13317216
	at com.dyuproject.protostuff.runtime.ObjectSchema.readObjectFrom(ObjectSchema.java:690)
	at com.dyuproject.protostuff.runtime.IdStrategy$8.mergeFrom(IdStrategy.java:454)
	at com.dyuproject.protostuff.CodedInput.mergeObjectEncodedAsGroup(CodedInput.java:271)
	at com.dyuproject.protostuff.CodedInput.mergeObject(CodedInput.java:239)
	at com.dyuproject.protostuff.runtime.IdStrategy$10.mergeFrom(IdStrategy.java:522)
	at com.dyuproject.protostuff.runtime.IdStrategy$10.mergeFrom(IdStrategy.java:1)
	at com.dyuproject.protostuff.runtime.ArraySchema.readObjectFrom(ArraySchema.java:194
测试用例重现
		bytes = Base64Utils.decode(data);
		invocation = serializer.deSerialize(bytes, TransactionInvocation.class);
data1 ok, data2 error

**Comment by 1991wangliang** [comment]
我用demo测试没有发现，能否提供一下代码？

**Comment by guiter** [comment]
遇到同样的问题，请问解决了吗

**Comment by guiter** [comment]
将redis中的data数据的空格字符替换成“+“ 则补偿成功，希望得到解决方案
data1：C5IBU2hhd2tleWVjbG91ZC5tb2R1bGVzLmNvbGxlZ2VjbG91ZC5hcnRpY2xlYmFzaWMuc2VydmljZS5pbXBsLkFydGljbGVCYXNpY1NlcnZpY2VJbXBsDBIPZGVsQXJ0aWNsZUJhc2ljG3oQamF2YS5sYW5nLk9iamVjdBgBEAEL gc6aGF3a2V5ZWNsb3VkLmNvbW1vbi5jb2xsZWdlY2xvdWQubW9kZWwuZW50aXR5LkFydGljbGVCYXNpYwjLHlgBegnojqvku4rnu7SBAbp0pspnAQAAigEGc3RyaW5nkAEADBwjeg9qYXZhLmxhbmcuQ2xhc3MYARABC5IBOmhhd2tleWVjbG91ZC5jb21tb24uY29sbGVnZWNsb3VkLm1vZGVsLmVudGl0eS5BcnRpY2xlQmFzaWMMJCrFAXB1YmxpYyBoYXdrZXllY2xvdWQuY29tbW9uLnV0aWwuSnNvbnAgaGF3a2V5ZWNsb3VkLm1vZHVsZXMuY29sbGVnZWNsb3VkLmFydGljbGViYXNpYy5zZXJ2aWNlLmltcGwuQXJ0aWNsZUJhc2ljU2VydmljZUltcGwuZGVsQXJ0aWNsZUJhc2ljKGhhd2tleWVjbG91ZC5jb21tb24uY29sbGVnZWNsb3VkLm1vZGVsLmVudGl0eS5BcnRpY2xlQmFzaWMp

data2：C5IBU2hhd2tleWVjbG91ZC5tb2R1bGVzLmNvbGxlZ2VjbG91ZC5hcnRpY2xlYmFzaWMuc2VydmljZS5pbXBsLkFydGljbGVCYXNpY1NlcnZpY2VJbXBsDBIPZGVsQXJ0aWNsZUJhc2ljG3oQamF2YS5sYW5nLk9iamVjdBgBEAEL+gc6aGF3a2V5ZWNsb3VkLmNvbW1vbi5jb2xsZWdlY2xvdWQubW9kZWwuZW50aXR5LkFydGljbGVCYXNpYwjLHlgBegnojqvku4rnu7SBAbp0pspnAQAAigEGc3RyaW5nkAEADBwjeg9qYXZhLmxhbmcuQ2xhc3MYARABC5IBOmhhd2tleWVjbG91ZC5jb21tb24uY29sbGVnZWNsb3VkLm1vZGVsLmVudGl0eS5BcnRpY2xlQmFzaWMMJCrFAXB1YmxpYyBoYXdrZXllY2xvdWQuY29tbW9uLnV0aWwuSnNvbnAgaGF3a2V5ZWNsb3VkLm1vZHVsZXMuY29sbGVnZWNsb3VkLmFydGljbGViYXNpYy5zZXJ2aWNlLmltcGwuQXJ0aWNsZUJhc2ljU2VydmljZUltcGwuZGVsQXJ0aWNsZUJhc2ljKGhhd2tleWVjbG91ZC5jb21tb24uY29sbGVnZWNsb3VkLm1vZGVsLmVudGl0eS5BcnRpY2xlQmFzaWMp

data1补偿失败，修改redis存储的数据data2，则补偿成功
