### ISSUE TITLE
希望可以支持手动关闭和开启TXC模式，并且有一套yml的配置示例

### ISSUE THREAD

**Issue by duyishuaixue** [codingapi/tx-lcn#218]
1. 系统可以支持txc模式的在配置文件中手动开启、关闭功能，不然启动的时候获取不到数据源就报错
2. 希望能有一套yml的配置示例
3. 特别是配置方面能有一个比较详细的说明，我们在使用的时候真的走了好多坑都是配置的问题
4.目前有的application-xxx.properties里面有些不需要的可以删除，最好只保留一个配置这样就比较明白清晰了

**Comment by 1991wangliang** [comment]
好的 你的问题我们会考虑。

**Comment by ujued** [comment]
1.  # 213 #212 会改善这个问题
2. properties 与 yml 只是格式问题 
3 and 4. application.properties为可运行最低配置，[详细配置见](https://txlcn.org/zh-cn/docs/setting/client.html)。请忽略application-xxx.properties
