### ISSUE TITLE
5.0 含有Redis操作的事务回滚问题

### ISSUE THREAD

**Issue by drakelee1221** [codingapi/tx-lcn#227]
A > B，
B中有一个db的insert和一个基于spring事务的redis操作，如果在A的方法最后抛出异常，两边的数据库事务是回滚了，但B的redis操作不会回滚。
正常单机情况下这个redis操作会随spring事务一起提交或回滚；
之前4.0由于db的connect会阻塞，所以并不会出现这个问题。
![a](https://user-images.githubusercontent.com/17973626/51723057-a65df400-2092-11e9-987c-b7585b072e49.png)
![b](https://user-images.githubusercontent.com/17973626/51723061-a958e480-2092-11e9-9dde-89f5ce826913.png)
![c](https://user-images.githubusercontent.com/17973626/51723062-abbb3e80-2092-11e9-83a5-ae00d12f68b9.png)

**Comment by meetzy** [comment]
哦 不好意思 你这个问题我看错了 如果你的insert方法出现 异常 我们是抛出的

**Comment by drakelee1221** [comment]
@meetzy A中最后一行的模拟的异常，有办法解决吗？B中的spring事务怎么同步回滚呢？

**Comment by meetzy** [comment]
TCC模式可以

**Comment by drakelee1221** [comment]
@meetzy 就是不想写TCC才用的LCN呢:cry:。。。
大致看了下LCN模式的源码，大致是：
代理了db的connection并设置了AutoCommit为false，将里面的commit、rollback和close都不做任何操作，在业务代码执行完毕后，等待tx-manager的通知；
整个过程，@LcnTransaction 注解的Around切面是包裹在spring注解事务Around切面的外层的，也就是说，如果业务代码没问题，在LCN执行等待tx-manager通知之前，spring事务的代码已经全部执行完毕（已正常提交），之后无论是收到tx-manager的通知是提交或是回滚，能操作的也只有之前代理的db的connection而已了；
理解不对的请指正。

所以提个建议，我在4.0中开始，就在建议使用spring的事务管理来做整个LCN的事务管理流程，这样的好处比局限于只用db的connection来要方便得多，能支持更多的spring组件；
或者试试将LCN事务管理放在spring注解事务Around切面的内一层，让LCN先等待tx-manager通知，再决定是否需要抛出异常让spring回滚。
望作者大神们考虑考虑。

**Comment by lynk-coder** [comment]
> @meetzy 就是不想写TCC才用的LCN呢。。。
> 大致看了下LCN模式的源码，大致是：
> 代理了db的connection并设置了AutoCommit为false，将里面的commit、rollback和close都不做任何操作，在业务代码执行完毕后，等待tx-manager的通知；
> 整个过程，@LcnTransaction 注解的Around切面是包裹在spring注解事务Around切面的外层的，也就是说，如果业务代码没问题，在LCN执行等待tx-manager通知之前，spring事务的代码已经全部执行完毕（已正常提交），之后无论是收到tx-manager的通知是提交或是回滚，能操作的也只有之前代理的db的connection而已了；
> 理解不对的请指正。
> 
> 所以提个建议，我在4.0中开始，就在建议使用spring的事务管理来做整个LCN的事务管理流程，这样的好处比局限于只用db的connection来要方便得多，能支持更多的spring组件；
> 或者试试将LCN事务管理放在spring注解事务Around切面的内一层，让LCN先等待tx-manager通知，再决定是否需要抛出异常让spring回滚。
> 望作者大神们考虑考虑。

其实我觉得还有一种方案，就是改写spring的事务拦截器。
