### ISSUE TITLE
Protocol message contained an invalid tag (zero)

### ISSUE THREAD

**Issue by sxyandapp** [codingapi/tx-lcn#228]
tx-manager报错如下：
io.netty.handler.codec.DecoderException: com.codingapi.txlcn.commons.exception.SerializerException: Protocol message contained an invalid tag (zero).

demo报错如下：
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 1048576: 168964404 - discarded

有谁遇到同样的问题吗？直接下载的例子，只改了配置，没改代码

**Comment by meetzy** [comment]
请保持TC与TM版本一致

**Comment by sxyandapp** [comment]
> 请保持TC与TM版本一致

对比了tc与tm的版本，确实不一直，多谢提醒。不过遇到了新问题，dubbo-demo-d和dubbo-demo-e里的事务不会回滚，我在研究研究
