### ISSUE TITLE
非springboot项目如何集成tx-client

### ISSUE THREAD

**Issue by sxyandapp** [codingapi/tx-lcn#229]
例子里都是基于springboot的，但由于历史原因，有些老项目不是springboot的，而且也不允许改成springboot项目，这种情况下，项目如何集成tx-client（dubbo项目）

**Comment by 1991wangliang** [comment]
目前我们的机制都是采用的springboot的形式，若非spring boot项目暂时是无法使用。

**Comment by sxyandapp** [comment]
我自己试试吧
