### ISSUE TITLE
微服务多节点注册TM，模块标识重复的问题

### ISSUE THREAD

**Issue by HongKing** [codingapi/tx-lcn#232]
请问下能否手动指定“模块标识”？现在默认是服务名+端口的模式，能否通过配置更换为IP+端口？场景如下：
假如服务名为TestA的微服务有两个节点A1和A2分别在两台机器上，为了管理方便及容灾，这两台机器的配置完全一样（除了IP），那么此时A1和A2注册到TM的模块标识都是“TestA:Port”，那么此时TM管理页面就会出现两条相同“模块标识”的记录，无法区分出哪个是A1，哪个是A2，假如其中一个挂掉，也无法区分出挂掉的是哪个。建议在线模块列表里面能显示如下三列“服务名，模块标识（为IP:Port格式），注册时间”，建议模块标识为IP+Port而不是服务名+Port，另外为了兼容多网卡，建议IP采用“spring.cloud.client.ip-address”获取

**Comment by 1991wangliang** [comment]
在5.0.2已修复

**Comment by zqWu** [comment]
这个是否是重复注册?
![image](https://user-images.githubusercontent.com/7589001/64679966-5e6bd000-d4af-11e9-99cb-8674764ac747.png)
