### ISSUE TITLE
#关于使用自定义Bean拦截器导致的事务无效问题#

### ISSUE THREAD

**Issue by lynk-coder** [codingapi/tx-lcn#252]
首先排除	
TransactionAutoConfiguration.class
的自动配置

定义自己的事务拦截器bean
 @Bean(name = "transactionInterceptor")
//    @ConditionalOnMissingBean
    public TransactionInterceptor transactionInterceptor(PlatformTransactionManager transactionManager) {
        Properties properties = new Properties();
        properties.setProperty("*", "PROPAGATION_REQUIRED,-Throwable");
        TransactionInterceptor transactionInterceptor = new TransactionInterceptor();
        transactionInterceptor.setTransactionManager(transactionManager);
        transactionInterceptor.setTransactionAttributes(properties);
        return transactionInterceptor;
    }

TM端DEBUG日志正常，
TC端提示 Non lcn connection when clear transaction.警告

因此导致分布式事务失效(但本地事务正常)
所以可能 A->B
A不提交，B被提交，的情况出现。

**Comment by lynk-coder** [comment]
不管用注解的事务模式还是使用拦截器的事务模式，均失效。

**Comment by ujued** [comment]
TransactionInterceptor 是在org/springframework/transaction/annotation/ProxyTransactionManagementConfiguration，这个ConfigurationBean中定义的吧

**Comment by zlklink** [comment]
我也遇到了这个问题  目前看来似乎是BUG

**Comment by 1991wangliang** [comment]
https://txlcn.org/zh-cn/docs/fqa.html

zlklink <notifications@github.com> 于 2019年2月25日周一 下午4:05写道：
