### ISSUE TITLE
#关于多数据源导致的LCN错误代理Connection的问题#

### ISSUE THREAD

**Issue by lynk-coder** [codingapi/tx-lcn#254]
com.codingapi.txlcn.tc.aspect.DataSourceAspect
里的
 @Around("execution(* javax.sql.DataSource.getConnection(..))")
    public Object around(ProceedingJoinPoint point) throws Throwable {
        return this.dtxResourceWeaver.getConnection(() -> {
            return (Connection)point.proceed();
        });
    }

会对
AbstractRoutingDataSource的getConnection()进行环绕的同时，
也会对DruidDataSource（类似的第三方数据源）的getConnection()进行环绕，

因为在AbstractRoutingDataSource里有个方法叫
    public Connection getConnection() throws SQLException {
        return this.determineTargetDataSource().getConnection();
    }
导致最后lcn错误的代理了connect

**Comment by ujued** [comment]
考虑在接下来的版本给出较完善的多数据源方案

**Comment by lynk-coder** [comment]
非常感谢

**Comment by 1991wangliang** [comment]
我们会在下一个版本中提供两种方式获取连接。  
1. 依旧是采用代理的方式。  
2. 我们提供一个可代理的连接池对象。

**Comment by KangSpace** [comment]
期待多数据源版本
