### ISSUE TITLE
5.0.1LCN模式不起作用

### ISSUE THREAD

**Issue by onlyougit** [codingapi/tx-lcn#255]
A服务代码： 
@Override
    @LcnTransaction
    @Transactional
    public String addOrder() {
        Order order = new Order();
        order.setOrderCode("O-0001");
        order.setStatus("1");
        //添加订单
        int result = orderMapper.addOrder(order);
        //调用B服务
        paymentFeign.addPayment();
       //让其报错
        System.out.println(1/0);
        log.info("order result="+result);
        return "success";
    }
B服务代码：
@Override
    @LcnTransaction
    @Transactional
    public String addPayment() {
        Payment payment = new Payment();
        payment.setPaymentCode("P-0001");
        payment.setPaymentAmount("55");
        //添加支付
        int result = paymentMapper.addPayment(payment);
        log.info("payment result="+result);
        return "success";
    }
结果：A服务回滚了；B服务提交了。这是为什么？

**Comment by onlyougit** [comment]
查看了日志，我发现A服务和B服务都成了发起方，因为都在create group

**Comment by ujued** [comment]
开了服务降级吧?  #129

**Comment by lynk-coder** [comment]
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
feign:
  hystrix:
    enabled: true

或者 

feign:
  hystrix:
    enabled: false

**Comment by lynk-coder** [comment]
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
feign:
  hystrix:
    enabled: true

或

feign:
  hystrix:
    enabled: true

**Comment by lynk-coder** [comment]
hystrix:
command:
default:
execution:
isolation:
strategy: SEMAPHORE
feign:
hystrix:
enabled: true

或

feign:
hystrix:
enabled: false

**Comment by HS-Z** [comment]
遇到同样的问题，设置feign.hystrix.enabled=false后，仍然不起作用

**Comment by onlyougit** [comment]
feign:
hystrix:
enabled: false
这样设置后我这边可以了，但是为什么呢，我的项目本身就需要做降级的呀
