### ISSUE TITLE
springcloud feign 开启负载均衡时的配置，相同的模块重复调用的问题

### ISSUE THREAD

**Issue by HongKing** [codingapi/tx-lcn#256]
按官方文档，做如下配置后
`tx-lcn.ribbon.loadbalancer.dtx.enabled=true`
如果某个服务在初次请求时没有准备好，在调用时，会返回“没有可用服务”，但隔一段时间再请求，还是同样的错误，如果将该配置改为false则正常。因此我猜测，此处应该时，没有重新从服务中心重新获取可用服务导致。此处我建议，在同一次请求中，服务使用同一个，但是不同请求应该从服务注册中心获取最新可用的服务

**Comment by 1991wangliang** [comment]
这个问题我们看一下。

**Comment by 1991wangliang** [comment]
我看一下代码，这个地方当请求响应以后会销毁存储对象的。应该不会存在你说的问题，我尝试测试了几次没有发现你的问题。请问你测试的版本是那个？
