### ISSUE TITLE
并发测试处理的事务量和预期的不同

### ISSUE THREAD

**Issue by yizhishang** [codingapi/tx-lcn#258]
比如：我并发1秒并发量500,引用官网的demo（全都是LCN模式，然后新建了2个数据库，demoD和demoE的数据分别插入到新建的库中）
结果是，3个库的数据数量都是相同（说明事务的一致性还是ok的），
这个并发量500，就是我期待处理事务的数量
每个库里数据量就是实际产生的事务量
两者并不相等

**Comment by 1991wangliang** [comment]
你能在QQ下给我私信一下吗？邀请你到开发者群里
