### ISSUE TITLE
5.0.1 版本springCloud 1.5 路由不起作用

### ISSUE THREAD

**Issue by helei810304** [codingapi/tx-lcn#260]
springcloud 1.5 似乎不能用到 路由切换类 TxlcnZoneAvoidanceRule

@Override
    public Server choose(Object key) {
        // 0. 非分布式事务直接执行默认业务.
        if (!TracingContext.tracing().hasGroup()) {
            return super.choose(key);
        }

        // 1. 自己加入此事务组调用链
        assert Objects.nonNull(registration);
        TracingContext.tracing().addApp(registration.getServiceId(), registration.getHost() + ":" + registration.getPort());

注意。。
, registration.getHost() + ":" + registration.getPort()

**这2个属性，在springCloud 1.5 的starter 里，没有这2个mehod，属于没向下兼容吧**

**Comment by 1991wangliang** [comment]
你用的是什么版本的？

**Comment by 1991wangliang** [comment]
springboot springcloud

**Comment by helei810304** [comment]
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.10.RELEASE</version>
        <relativePath/> 
    </parent>


<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Dalston.SR5</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

**Comment by 1991wangliang** [comment]
你可以尝试修改

```
    <properties>       
        <txlcn-org.springframework.cloud.commons.version>1.3.5.RELEASE</txlcn-org.springframework.cloud.commons.version>
    </properties>
```

**Comment by 1991wangliang** [comment]
![image](https://user-images.githubusercontent.com/5245347/53552278-efafd080-3b75-11e9-86d3-69af497e0c4e.png)
建议升级springcloud 版本到 Edgware.SR5。也是基于springboot1.5.x
