### ISSUE TITLE
Non lcn connection when clear transaction.

### ISSUE THREAD

**Issue by abcpopop** [codingapi/tx-lcn#262]
使用lcn模式一直报错，Non lcn connection when clear transaction.，请问怎么配置connection的代理

**Comment by 1991wangliang** [comment]
https://txlcn.org/zh-cn/docs/fqa.html

abcpopop <notifications@github.com> 于 2019年2月25日周一 下午6:00写道：

**Comment by laimingzhang** [comment]
官网中的FQA解决不了这个问题，有哪位大神有其他的解决方案吗？

**Comment by 1991wangliang** [comment]
https://github.com/1991wangliang/bank-demo
看视频，末尾部分。
