### ISSUE TITLE
关于TM集群问题

### ISSUE THREAD

**Issue by ccllxw2** [codingapi/tx-lcn#265]
1.看文档介绍，TC要保证所输入的所有TM正常才能正常启动，那如果其中一个TM挂了，是不是会导致后面的TC无法启动
2.在运行过程中，有TM挂了，对已运行的TC有什么影响？
3.新增TM节点，已经运行的TC 需要改配置重启吗？ 如果不需要，它是怎么通知到其他TC的

**Comment by 1991wangliang** [comment]
TC 启动时要求所有配置项在内的TM必须可以正常连接。若无法连接TC将启动不成功。

TC运行时出现TM挂了，TC会重连次数可配置。TC下只有有一个TM保持连接就不会影响TC的工作。当新的TM启动时TC会自动连接上。这里的TM无论是否在TC的配置下都会连接。当前前提时所有的TM的Redis时共享的。
