### ISSUE TITLE
关于tm5.0.1 集群的问题

### ISSUE THREAD

**Issue by helei810304** [codingapi/tx-lcn#269]
启动以后，看到tm 的 webconsole ，不知道tm 的集群包含了哪些机器，能否显示下集群详细信息

**Comment by 1991wangliang** [comment]
这个问题我们可以增加上。感谢建议

**Comment by ujued** [comment]
5.0.2.RELEASE版本，/admin/tm-cluster这个API会提供TM Cluster信息，但是木有UI。后续版本再对接上UI。^_^
