### ISSUE TITLE
tx-4.2 tx:manager:loadbalance:类型 key 没有过期时间

### ISSUE THREAD

**Issue by duanyingchao** [codingapi/tx-lcn#271]
- [x] I have searched the [issues](https://github.com/codingapi/tx-lcn/issues) of this repository and believe that this is not a duplicate.

### 1. Bug Description
tx-4.2 tx:manager:loadbalance:类型 key 没有过期时间,长时间运行后 redis 里边key 过多，导致 tx-manager 查询缓慢.如何为 tx:manager:loadbalance设置过期时间

### 2. Environment:
- JDK version:1.8
- OS:centos7
- TX-LCN version:4.2
- Others:

### 3. Exception Stacktrace

```
Paste your Exception Stacktrace here!
```

**Comment by 1991wangliang** [comment]
可否将项目升级到5.x？

**Comment by duanyingchao** [comment]
5.X 已经在测试，目标版本为5.0.2。但上线替换周期较长。目前想到的解决方案是重新编译4.2版本。但是对loadbalance的生命周期不是很理解，所以不知道从哪个地方清除key

**Comment by duanyingchao** [comment]
目前4.2已经在 线上实施，约20天左右，业务会出现大量回滚。清除tx 相关key，并重启后业务恢复正常

**Comment by 1991wangliang** [comment]
https://github.com/codingapi/tx-lcn/blob/last.4.2/transaction-springcloud/src/main/java/com/codingapi/ribbon/loadbalancer/LcnLoadBalancerRule.java

这里当时没有做清理操作，若修改的话可以在TM 保存模块信息时设置清理时间。建议清理时间大于分布式事务最大时间即可。

**Comment by duanyingchao** [comment]
已解决，谢谢！
