### ISSUE TITLE
5.0.2 的tm ，部署到centos ，socket不通

### ISSUE THREAD

**Issue by helei810304** [codingapi/tx-lcn#277]
5.0.2 的tm ，部署到centos ，socket不通
5.0.1 的tm ，部署到同样的机器，可以用

**Comment by ujued** [comment]
5.0.2TM对主机的绑定做了限制，需要明确制定绑定的主机。
解决方法：TM配置 `tx-lcn.manager.host=x.x.x.x`指定具体要绑定的主机

**Comment by helei810304** [comment]
设置了，仍然不成功！

**Comment by helei810304** [comment]
设置成了具体的ip 就可以了，设置成 127.0.0.1 就不成功，你们的文档得更新了！！！
