### ISSUE TITLE
springcloud 整合lcn，每次都是产生新的groupId，无法回滚事务

### ISSUE THREAD

**Issue by maxSong1111** [codingapi/tx-lcn#279]
- [ ] I have searched the [issues](https://github.com/codingapi/tx-lcn/issues) of this repository and believe that this is not a duplicate.

### 1. Bug Description
使用aop的方式，调用不同的模块都是产生新的groupId，导致不能回滚事务

### 2. Environment:
- JDK version:1.8
- OS:
- TX-LCN version:5.0.2.RELEASE
- Others:

### 3. Exception Stacktrace

serviceA 调用serviceB，我看两个服务的后台日志 的groupId 都是不同的 ，请问是什么原因

```
Paste your Exception Stacktrace here!
```

**Comment by PowellZhang** [comment]
请问下这个问题怎么解决的？

**Comment by maxSong1111** [comment]
试下这个






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "codingapi/tx-lcn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月30日(星期三) 下午5:53
收件人:&nbsp;"codingapi/tx-lcn"<tx-lcn@noreply.github.com&gt;;
抄送:&nbsp;"457209828"<457209828@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [codingapi/tx-lcn] springcloud 整合lcn，每次都是产生新的groupId，无法回滚事务 (#279)





 
请问下这个问题怎么解决的？
