### ISSUE TITLE
5.0.2 的tm，一定要设置本机的具体 ip，运维看了傻眼了

### ISSUE THREAD

**Issue by helei810304** [codingapi/tx-lcn#281]
5.0.2 的tm，一定要设置本机的ip
tx-lcn.manager.host=10.0.0.67

我们公司打算tm部署4个机器集群，这样的话是不是要分开build啊。。

**Comment by nimeijian** [comment]
https://github.com/codingapi/tx-lcn/issues/261

**Comment by ujued** [comment]
配置与build？什么意思
