### ISSUE TITLE
用5.0.2跑 springCloud 的demo，但是lcn 似乎没一点作用，都插入成功了

### ISSUE THREAD

**Issue by helei810304** [codingapi/tx-lcn#284]
用5.0.2跑 springCloud 的demo，但是lcn 似乎没一点作用，都插入成功了,qq 444076352，求加，给你我的demo

**Comment by helei810304** [comment]
忽略把，分布式的回滚系统的数据源一定要用阿里的  DruidDataSource ？我用了其他的似乎就不行了

**Comment by 1991wangliang** [comment]
你可以看一下我的讲解视频的尾部，里面有提到对于无法管理的处理。https://github.com/1991wangliang/bank-demo
