### ISSUE TITLE
5.0.2  tm 集群不能自动扩容

### ISSUE THREAD

**Issue by helei810304** [codingapi/tx-lcn#292]
我先设置了一个tm ，然后3个 业务 app 启动，又扩展了一个tm 
结果业务app 感知不到新增的tm

**Comment by ujued** [comment]
有什么异常日志可以提供吗？

**Comment by helei810304** [comment]
没任何日志。。
比如我配置了一个节点的tm ，如果我再加一个节点，文档说可以自动扩容

但是我看了下日志，一个请求都没到新tm 上去。。

**Comment by ujued** [comment]
一个Redis吗？

**Comment by helei810304** [comment]
对的，一个redis

**Comment by ujued** [comment]
com.codingapi.txlcn.tm.cluster.TMAutoCluster，这里是TM加入集群的逻辑。
