### ISSUE TITLE
单个TM时，当TM挂掉后时间超过8次重试的时间...

### ISSUE THREAD

**Issue by keynescao** [codingapi/tx-lcn#293]
单个TM时，当TM挂掉后时间超过8次TC重连的时间,这时再去启动TM，那么TC是不能自动注册上。如果在实际业务场景中出现这种情况就得重启各个TC端，请问是否可以配置成一直重连呢？

**Comment by 17369644** [comment]
我也遇到这个问题，目前只有设置大量的重连次数

**Comment by ujued** [comment]
TM集群就好了

**Comment by 17369644** [comment]
如果集群都挂了。在特定时间没启来。那不是tc都必须重启

**Comment by ujued** [comment]
你需要保证集群时刻至少有一台正常的TM，失败的TM重启后自动进入集群
