### ISSUE TITLE
LCN 模式，数据不一致问题

### ISSUE THREAD

**Issue by helei810304** [codingapi/tx-lcn#299]
昨天做demo 压测，中间kill 掉 client 的虚拟机，发现数据不一致的情况出现

见源码 SimpleTransactionManager的 notifyTransaction方法
大概是这样
for(TransactionUnit unit :  unitList){
      //比如提醒各个参与lcn 的app，提交datassource
      MessageDto respMsg =
                            rpcClient.request(callNettyIp, MessageCreator.notifyUnit(notifyUnitParams));

}

有如下场景，总共有4个端要提交，前面2个成功了，第三个机器shutdown 了，然后第一个和第二个，也不会做补偿删除（比如 txc 模式），导致数据不一致

这样的问题带来的直接结果
1  不敢随意停机发布，运维一般都是kill －9 的
2 tm 也不敢随意停

建议
能否将 txc 模式 和 lcn 模式结合一下，把undolog  放到中心库（比如mysql），然后lcn 已经提交的参与方，能否在一定时间后，去检查下整个分布式事务的状态（比如放在redis 里），如果没执行成功，则效仿 txc 模式，做undo 操作

但是这里又有个问题，如果已经提交的事务，在提交  和 撤销 这段时间内，被其他程序线程修改了，则不能回滚，因此在 undo 的时候，还要加个check 比对数据 的过程

**Comment by ujued** [comment]
宕机后需要检查TC端的AspectLog，来手动作补偿(Insert Delete)最终一致。Update 操作可能会造成最终数据不一致，这个地方可以在TM控制下由于宕机而某个失败的事务组成员在服务重启前不参与分布式事务，但是服务可用性就得不到保障了
