### ISSUE TITLE
lcn 的服务端回调问题

### ISSUE THREAD

**Issue by helei810304** [codingapi/tx-lcn#301]
看了下源码 ,TransactionUnit 似乎是  java 的 method 的本地签名生产的md5
然后在lcn 模式中，一个业务的参与方，可能会有多个 Transaction

导致在回调的过程中，会有多次无效回调
能否在区分下lcn 模式，如果是lcn 模式，按照 application_id 来做一次回调就可以了

如果是txc 模式，则可以多次回调

**Comment by ujued** [comment]
一次分布式事务下每个模块都会且只会参与一次分布式事务。
