### ISSUE TITLE
txc模式查询数据快照异常

### ISSUE THREAD

**Issue by register2hard** [codingapi/tx-lcn#303]
运行环境springboot+dubbo2.66，使用的是TXC模式，执行select语句查询数据快照错误，表达式中多拼接了一个逗号
这是我执行的更新操作：
![9ZFP7TSB}QW271`@KSD`D5D](https://user-images.githubusercontent.com/38393638/54172822-5f00bb00-44ba-11e9-83af-9a1d57bff8db.png)
这是异常信息：
![6L3SN4Y8PZP$UP4EJ_S`RGE](https://user-images.githubusercontent.com/38393638/54172825-60ca7e80-44ba-11e9-9d8f-dd095dfd3db3.png)

**Comment by ujued** [comment]
好的谢谢！#270
