### ISSUE TITLE
为什么不提供一个补偿性的事务？do->undo

### ISSUE THREAD

**Issue by lnnnogithub** [codingapi/tx-lcn#307]
为什么不提供一个补偿性的事务？do->undo

**Comment by lnnnogithub** [comment]
不是基于日志的，是基于方法的，两个方法，像Easytransaction那样-->doCompensableBusiness和compensation

**Comment by ujued** [comment]
目前做到的是对确定能补偿的过程做自动补偿，其他的需要管理员根据TM异常记录，TC切面日志等做手动补偿
