### ISSUE TITLE
springcloud微服务端tc的manager-address怎么指向eureka的tx-manager

### ISSUE THREAD

**Issue by 17369644** [codingapi/tx-lcn#309]
lcn 5.02版本
springcloud微服务端tc的manager-address怎么指向eureka的tx-manager
是否只能写死，例如现在是这样
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070,127.0.0.1:8071
能不能指向到eureka的注册服务上，实现自动切换

**Comment by 17369644** [comment]
5.02版本好像不用配置，只要都是注册到同一个eureka上面就能自动分配到tm

**Comment by ujued** [comment]
集群地址可以配置一个，AutoCluster会与集群作连接
