### ISSUE TITLE
事务存储有问题

### ISSUE THREAD

**Issue by liubo988** [codingapi/tx-lcn#312]
- [ ] I have searched the [issues](https://github.com/codingapi/tx-lcn/issues) of this repository and believe that this is not a duplicate.

### 2. Environment:
- JDK version:
- OS:
- TX-LCN version:
- Others:

### 3. Exception Stacktrace

```
Paste your Exception Stacktrace here!
```

**Comment by liubo988** [comment]
2个事务模块，A，B，A调用B ，先保存B，再保存A。结果只有B插入成功，A失败。但是没有报错。什么情况？

**Comment by ujued** [comment]
...
