### ISSUE TITLE
tc5.02保存如果主键不是自增，PrimaryKeyListVisitor抛空异常

### ISSUE THREAD

**Issue by 17369644** [codingapi/tx-lcn#315]
CREATE TABLE `tg_merchant_site_config` (
  `lv_top_id` int(11) NOT NULL COMMENT '商户号,商户ID，member表的id',
  `lv_top_name` varchar(30) DEFAULT NULL COMMENT '商户名称',
  `site_name` varchar(100) DEFAULT NULL COMMENT '站点名称'
  PRIMARY KEY (`lv_top_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商户站点配置表';
表结构如上，如tc里面保存的时候PrimaryKeyListVisitor类newKeyValues方法的
59行Object expression = ((Expression)expressions.get(i)).getASTNode().jjtGetValue();
会抛一个空异常。不知道为什么，是不是必须主键需要自增id作为标识

**Comment by i-tudou** [comment]
我遇到的问题和你一样呢，不知道是什么情况，你的解决了吗？

**Comment by 17369644** [comment]
我之前这个问题是因为我注解用错了。我是5.0.2，用@LcnTransaction就没问题了。你估计是用的@TxcTransaction

**Comment by i-tudou** [comment]
它5.0之后不是支持LCN/TXC/TCC三种模式吗，你换成LCN模式还是没有解决问题呀，我现在就是要跟进5.0之后的版本，现在测试TXC模式遇到的这个问题。LCN模式是没有问题的。
