### ISSUE TITLE
lcn模式下 事物回滚问题

### ISSUE THREAD

**Issue by hiphor** [codingapi/tx-lcn#316]
使用的最新5.0.2版本，spring boot2.1.0，jdbc
场景:服务a开启分布式事物，通过feign调用服务b，
服务b也开启了分布式事物。
该场景下如果只在服务a中抛出异常，a中事物和b中的事物都会回滚。
而如果只在服务b中抛出异常，b中事物回滚，而a中事物则提交成功。
请问这是lcn模式决定的还是我的配置方面存在问题？

**Comment by hiphor** [comment]
是自建项目非demo项目

**Comment by ningyongli** [comment]
b服务有没有使用try catch，我认为把让a服务知道抛出了异常就可以了

**Comment by hiphor** [comment]
这的确是种方法，但我想知道在lcn模式下除了分布式事务发起方异常回滚外，还有别的方式让其回滚吗

**Comment by ningyongli** [comment]
这个问题我刚才测试了，是可以回滚的，我不知道出了什么问题，不可以回滚

**Comment by ningyongli** [comment]
不知道是不是DataSourceAspect的问题导致，可以debug一下看看

**Comment by hiphor** [comment]
> 这个问题我刚才测试了，是可以回滚的，我不知道出了什么问题，不可以回滚

你是让a中抛出异常吗？

**Comment by ningyongli** [comment]
不是，我只是让服务b正常报错，a服务会知道b服务抛出的异常
这是a中输出的异常信息
````
feign.FeignException: status 500 reading UserService#testCustomer(String); content:
{"timestamp":1553066491078,"status":500,"error":"Internal Server Error","message":"String index out of range: 15","path":"/v1/customers/test"}
	at feign.FeignException.errorStatus(FeignException.java:60)
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:89)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:143)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:77)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:102)
	at com.sun.proxy.$Proxy207.testCustomer(Unknown Source)
	at 
.......
org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)

```

这个异常实际上是b服务抛出的，当然我没有写熔断histrix返回信息

> > 这个问题我刚才测试了，是可以回滚的，我不知道出了什么问题，不可以回滚
> 
> 你是让a中抛出异常吗？

**Comment by hiphor** [comment]
> 不是，我只是让服务b正常报错，a服务会知道b服务抛出的异常
> 这是a中输出的异常信息
> 
> ```
> feign.FeignException: status 500 reading UserService#testCustomer(String); content:
> {"timestamp":1553066491078,"status":500,"error":"Internal Server Error","message":"String index out of range: 15","path":"/v1/customers/test"}
> 	at feign.FeignException.errorStatus(FeignException.java:60)
> 	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:89)
> 	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:143)
> 	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:77)
> 	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:102)
> 	at com.sun.proxy.$Proxy207.testCustomer(Unknown Source)
> 	at 
> .......
> org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
> 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
> 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
> 
> ```
> 
> 这个异常实际上是b服务抛出的，当然我没有写熔断histrix返回信息
> 
> > > 这个问题我刚才测试了，是可以回滚的，我不知道出了什么问题，不可以回滚
> > 
> > 你是让a中抛出异常吗？
> ```

谢谢
