### ISSUE TITLE
【manager挂掉之后，客户端不断连接，占用大量的内存】

### ISSUE THREAD

**Issue by jgslvwy** [codingapi/tx-lcn#318]
1.在准生产环境，挂上V4.1.0版本的TX-CLIENT，机器内存32G，刚开始没启动TX-MANAGER,在连接TX-MANAGER之后，再次启动MANAGER，发现内存飙升

**Comment by jgslvwy** [comment]
@ #186

**Comment by ujued** [comment]
抱歉，4.x不再维护了。V5.0.2可以有效改善这些问题
