### ISSUE TITLE
补偿机制的一点疑问

### ISSUE THREAD

**Issue by MrJiangxh** [codingapi/tx-lcn#32]
1.补偿决策，2.补偿结果通知
这两种补偿模式有什么区别？
对应的接收接口需要怎么处理？
能说明下吗？谢谢

**Comment by 1991wangliang** [comment]
首先前提是开启了补偿，然后在出现补偿的时候会先执行补偿决策，当返回success才会执行补偿。然后将补偿结果通知给补偿服务。
