### ISSUE TITLE
请问如何控制事物手动回滚?

### ISSUE THREAD

**Issue by persistGithub** [codingapi/tx-lcn#34]
类似于 Spring的 TransactionAspectSupport.currentTransactionStatus().setRollbackOnly();     因为不一定是异常才需要回滚,我没有在文档上看到手动回滚的东西  谢谢

**Comment by 1991wangliang** [comment]
https://github.com/codingapi/tx-lcn/blob/master/tx-client/src/main/java/com/codingapi/tx/control/LCNTransactionAspectSupport.java

**Comment by persistGithub** [comment]
我现在有一个业务,需要在新建用户后进行其它的用户相关信息的保存,是两个不同的业务实体和spring boot
 服务 ,后面的用户信息关联了保存的用户ID,使用的是JPA, 我看到tx的日志是在commit,但是会一直insert user
最后报错,,

**Comment by persistGithub** [comment]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction

**Comment by persistGithub** [comment]
lcn transaction over, res -> groupId:jOlZWY7E and  state is rollback

**Comment by 1991wangliang** [comment]
是不是出现了两个模块操作同一行数据的情况了？

**Comment by 1991wangliang** [comment]
LCNTransactionAspectSupport. currentTransactionStatus(). setRollbackOnly();

**Comment by 1991wangliang** [comment]
事务手动回滚

**Comment by persistGithub** [comment]
C是一个公共服务,A服务和B服务都引用了他  A服务新建一条数据,B服务中将这个条数据的ID设置为关联关系,在C服务中保存 就不行 会保存 而且是多次循环插入

**Comment by persistGithub** [comment]
C服务不是web服务.没有配置数据源

**Comment by 1991wangliang** [comment]
C 是操作数据源的服务？
