### ISSUE TITLE
springcloud demo启动不成功

### ISSUE THREAD

**Issue by sxjsxj1994** [codingapi/tx-lcn#37]
wiki中的4.0.0在maven库中没有。。
用4.0.1和4.0.2 均发现空指针异常。断点追踪到时txserver为空。
![default](https://user-images.githubusercontent.com/22607591/34813178-e21f80a0-f6e3-11e7-868e-1d51bd2a78bb.png)
如果用4.0.3则在编译时就出错了
![2](https://user-images.githubusercontent.com/22607591/34813201-fcb6063c-f6e3-11e7-9db7-8dc7bb768098.png)

**Comment by sxjsxj1994** [comment]
断点发现是getServer那里为空。用的tx-manager是4.0.3的。。请问如何解决
![3](https://user-images.githubusercontent.com/22607591/34814304-196b9a72-f6e8-11e7-84f1-4f0372e0d9e5.png)

**Comment by 1991wangliang** [comment]
执行的时候一定要确保版本与TxManager一直
