### ISSUE TITLE
springcloud2 springboot 2.1.4 yml 配置总是不成功 只能用 application.properties

### ISSUE THREAD

**Issue by codeyung** [codingapi/tx-lcn#372]
用application.properties 之后配置成功 jmeter 测试都可以通过 yml 会报数据库连接失败
读取方式的问题吗 ？用了yml 还是走源码里的配置了好像 = =
https://github.com/codeyung/hex-springcloud/tree/master/tx-manager/src/main/resources

**Comment by codeyung** [comment]
还有我注册 Eureka 里面有一个tx-manager  
在启动一个微服务 注册之后 
tx的后台在线模块列表显示2个相同的微服务
可是我明明就一个

**Comment by langmnm** [comment]
你这两个问题我都遇到了。

**Comment by langmnm** [comment]
解决方案：
问题1. 如果你是自建工程，引入了TM，那么你需要创建一个 resources/application.properties 空文件，这个时候就会读取yml文件了。
问题2. 目前我这边的现象是有时显示1个，有时显示两个，没有找到具体原因，但是目前没发现有什么影响，可以正常使用。

一直期待发布新版本～

**Comment by roobc** [comment]
> 解决方案：
> 问题1. 如果你是自建工程，引入了TM，那么你需要创建一个 resources/application.properties 空文件，这个时候就会读取yml文件了。
> 问题2. 目前我这边的现象是有时显示1个，有时显示两个，没有找到具体原因，但是目前没发现有什么影响，可以正常使用。
> 
> 一直期待发布新版本～

我有空试一下 今天去面试QAQ

**Comment by codeyung** [comment]
> 解决方案：
> 问题1. 如果你是自建工程，引入了TM，那么你需要创建一个 resources/application.properties 空文件，这个时候就会读取yml文件了。
> 问题2. 目前我这边的现象是有时显示1个，有时显示两个，没有找到具体原因，但是目前没发现有什么影响，可以正常使用。
> 
> 一直期待发布新版本～

谢谢 提醒  我有空测试一下  最近在投简历 准备面试 = =

**Comment by VanHelxing** [comment]
> 解决方案：
> 问题1. 如果你是自建工程，引入了TM，那么你需要创建一个 resources/application.properties 空文件，这个时候就会读取yml文件了。
> 问题2. 目前我这边的现象是有时显示1个，有时显示两个，没有找到具体原因，但是目前没发现有什么影响，可以正常使用。
> 
> 一直期待发布新版本～

> 解决方案：
> 问题1. 如果你是自建工程，引入了TM，那么你需要创建一个 resources/application.properties 空文件，这个时候就会读取yml文件了。
> 问题2. 目前我这边的现象是有时显示1个，有时显示两个，没有找到具体原因，但是目前没发现有什么影响，可以正常使用。
> 
> 一直期待发布新版本～

我也是配置文件是YML格式，一直报找不到driver-class-name，创建一个空的application.properties文件就正常启动了。

**Comment by jack80342** [comment]
我也是配置文件是YML格式，一直报找不到driver-class-name，创建一个空的application.properties文件就正常启动了。

**Comment by jack80342** [comment]
有进展吗？我们的Spring Boot版本是2.1.8，Spring Cloud版本是Greenwich SR3也出现了读取不了yaml文件的问题。但是，放个空的properties文件就好了。之后问了搞配置中心，发现一定要把bootstrap.yml文件里的spring.application.name属性移到application.properties文件才能读取到。

**Comment by codeyung** [comment]
> 有进展吗？我们的Spring Boot版本是2.1.8，Spring Cloud版本是Greenwich SR3也出现了读取不了yaml文件的问题。但是，放个空的properties文件就好了。之后配了配置中心，发现一定要把bootstrap.yml文件里的spring.application.name属性移到application.properties文件才能读取到。

是这样的 现在好像还没有修复

**Comment by PurestAsh** [comment]
> > 解决方案：
> > 问题1. 如果你是自建工程，引入了TM，那么你需要创建一个 resources/application.properties 空文件，这个时候就会读取yml文件了。
> > 问题2. 目前我这边的现象是有时显示1个，有时显示两个，没有找到具体原因，但是目前没发现有什么影响，可以正常使用。
> > 一直期待发布新版本～
> 
> > 解决方案：
> > 问题1. 如果你是自建工程，引入了TM，那么你需要创建一个 resources/application.properties 空文件，这个时候就会读取yml文件了。
> > 问题2. 目前我这边的现象是有时显示1个，有时显示两个，没有找到具体原因，但是目前没发现有什么影响，可以正常使用。
> > 一直期待发布新版本～
> 
> 我也是配置文件是YML格式，一直报找不到driver-class-name，创建一个空的application.properties文件就正常启动了。

谢谢！已解决！
