### ISSUE TITLE
自动补偿机制需要业务方如何操作使用？

### ISSUE THREAD

**Issue by eddy-zhou** [codingapi/tx-lcn#38]
请问下自动补偿机制需要业务方如何操作使用，以及tm.compensate.notifyUrl这个配置的地址？

**Comment by 1991wangliang** [comment]
1.为什么需要事务补偿？

事务补偿是指在执行某个业务方法时，本应该执行成功的操作却因为服务器挂机或者网络抖动等问题导致事务没有正常提交，此种场景就需要通过补偿来完成事务，从而达到事务的一致性。

2.补偿事务如何执行？
LCN的补偿事务原理是模拟上次失败事务的请求，然后传递给TxClient模块然后再次执行该次请求事务


3.自动补偿机制是什么?

1.首先自动补偿是需要在TxManager下通过tm.compensate.auto 参数开启的。当开启以后并且出现事务补偿的时候，就会触发自动补偿机制

2.当触发补偿的时候，LCN-TXManager会将补偿的切面信息传递给决策模块，也就是发起请求访问tm.compensate.notifyUrl的地址。传递的参数见说明，仅当返回值若为"success"时，自动补偿才会执行。

3.当自动补偿执行以及会将补偿结果通知给补偿决策服务器，还是通过tm.compensate.notifyUrl地址发送数据。（若补偿失败的情况，LCN会补偿3次尝试，每次间隔时间为tm.compensate.tryTime，若三次还是失败则补偿还会存在TxManager的补偿记录下，可通过手动或者TxManager后台继续对事务做补偿处理）。
