### ISSUE TITLE
当tm重启后 tc怎么才能自动重新注册上tm中

### ISSUE THREAD

**Issue by 862618936** [codingapi/tx-lcn#390]
当我重新启动tm时候 已注册的tc就没有了

**Comment by yangjwInRiver** [comment]
代码里面写的是tm挂了以后，tc的netty回调channelinactive会进行回调，然后在里面会进行重试，重试8次每次间隔6s，没连上的话就会在SocketManager里面把对应channels剔除掉。
你这种情况就是tm是单实例的情况，如果是多tm的情况就算过了上面的重试，在重启后也会通知另外的tm的tc去链接这个新启动的tm的

**Comment by javacoderxxp** [comment]
> 代码里面写的是tm挂了以后，tc的netty回调channelinactive会进行回调，然后在里面会进行重试，重试8次每次间隔6s，没连上的话就会在SocketManager里面把对应channels剔除掉。
> 你这种情况就是tm是单实例的情况，如果是多tm的情况就算过了上面的重试，在重启后也会通知另外的tm的tc去链接这个新启动的tm的

请问：tc重连的配置在哪？

**Comment by yizhishang** [comment]
这个问题已经修复了
