### ISSUE TITLE
请问下 hibernate_sequence  这个表是干啥用的  看代码 没有找到使用的

### ISSUE THREAD

**Issue by 862618936** [codingapi/tx-lcn#393]

**Comment by younk-zhao** [comment]
你这问题问的太没质量了,首先说解决方法：加上该配置，
spring.jpa.properties.hibernate.id.new_generator_mappings=false。

解释：报这个错是因为TxException这个类的主键生成规则为GenerationType.AUTO,在hibernate5中这个属性默认为true，当这个属性为true时，对于生成规则为GenerationType.AUTO的主键，数据库会自动的去寻找hibernate_sequence这张表，从这张表中产生主键。
