### ISSUE TITLE
LcnRibbonConfiguration 问题

### ISSUE THREAD

**Issue by Clark911** [codingapi/tx-lcn#40]
## 问题描述
加了 transaction-springcloud之后，eureka上服务的ip和端口变了，restTempLate 调用的还是老的ip和端口

## 解决办法
去除TransactionConfiguration类上的
@RibbonClients(defaultConfiguration=LcnRibbonConfiguration.class) 注解
去除
LcnRibbonConfiguration 的@ComponentScan 注解

**Comment by foxdd** [comment]
如果单纯去掉注解，负载均衡算法就不会运用，你是在一次请求内的ip和端口变化了么

**Comment by foxdd** [comment]
我修改了一下获取服务实例的方法，动态获取服务实例，比之前更新更快，后面merge到master上以后可以试试看
