### ISSUE TITLE
5.0.2 txlcn-tm项目下载源码后打出来的包有问题，才600多Kb，启动时报txlcn-tm-5.0.2.RELEASE.jar中没有主清单属性

### ISSUE THREAD

**Issue by ltlwill** [codingapi/tx-lcn#425]
- [ ] I have searched the [issues](https://github.com/codingapi/tx-lcn/issues) of this repository and believe that this is not a duplicate.

### 1. Bug Description
按照官网教程从 git clone https://github.com/codingapi/tx-lcn.git 下载源码后手动编译打包，打出来的包结构不对，体积只有600多KB，也启动不了，报：txlcn-tm-5.0.2.RELEASE.jar中没有主清单属性 

### 2. Environment:
- JDK version: 1.8
- OS: windows 7
- TX-LCN version: 5.0.2
- Others: maven 3.3.3

### 3. Exception Stacktrace

```
Paste your Exception Stacktrace here!
```

**Comment by david0718** [comment]
为什么没有回答，直接close
