### ISSUE TITLE
为什么你们这个框架这么垃圾啊  ，然后提bug也不改,加你们开发群,全是死人？？？一个人不说话？？？

### ISSUE THREAD

**Issue by cwm3412638** [codingapi/tx-lcn#436]
- [ ] I have searched the [issues](https://github.com/codingapi/tx-lcn/issues) of this repository and believe that this is not a duplicate.

### 2. Environment:
- JDK version:
- OS:
- TX-LCN version:
- Others:

### 3. Exception Stacktrace

```
Paste your Exception Stacktrace here!
```

**Comment by catman002** [comment]
有源码，自己修改嘛。
