### ISSUE TITLE
有点受不了了

### ISSUE THREAD

**Issue by 18705320883** [codingapi/tx-lcn#479]
- [ ] I have searched the [issues](https://github.com/codingapi/tx-lcn/issues) of this repository and believe that this is not a duplicate.

### 1. Bug Description
com.codingapi.txlcn.txmsg.exception.RpcException: request fail. non tx-manager is alive.

### 2. Environment:
- JDK version:
- OS:
- TX-LCN version:
- Others:

### 3. Exception Stacktrace

```
Paste your Exception Stacktrace here!
```

**Comment by 1991wangliang** [comment]
很抱歉给你带来的不变 😊
