### ISSUE TITLE
官网的【事务控制原理】文字描述错误？

### ISSUE THREAD

**Issue by wangbinlin** [codingapi/tx-lcn#482]
**官网的【事务控制原理】文字描述错误？**
http://www.txlcn.org/zh-cn/docs/principle/control.html
**错误地点：**

【事务控制原理 】描述错误，我在下面 **加粗** 标注了  

TX-LCN由两大模块组成, TxClient、TxManager，TxClient作为模块的依赖框架，提供TX-LCN的标准支持，TxManager作为分布式事务的控制 **放** 。事务发起方或者参与 **反** 都由 **TxClient** 端来控制。

**纠正建议：**（方，方，TxManager）

TX-LCN由两大模块组成, TxClient、TxManager，TxClient作为模块的依赖框架，提供TX-LCN的标准支持，TxManager作为分布式事务的控制 **方** 。事务发起方或者参与 **方** 都由 **TxManager** 端来控制。

**Comment by 1991wangliang** [comment]
收到。
