### ISSUE TITLE
框架优化第一次会议

### ISSUE THREAD

**Issue by 1991wangliang** [codingapi/tx-lcn#484]
时间：2019年12月26日 晚 10点 -12点
议题
  1.当前框架的问题；  
  2.优化方案；  
  3.去掉TM可行性及方案。  

将在QQ群里发起语音方式讨论方式。   

为了节省讨论时间，请先提前准备一下，大家有时间可参与进来的请留意回复下。  

框架原理视频介绍：   
https://www.bilibili.com/video/av80626430     
https://www.bilibili.com/video/av80676649    
https://www.bilibili.com/video/av80676836    

框架维护者群:421324785 ,若只是技术交流请加交流群。  

2019.12.26日会议  纪要
1、负载问题的优化
*  问题描述：
  负载的问题目前是由于LCN的有状态导致在模块负载的情况调用到了其他的模块将可能出现锁表问题。详细描述可见 https://www.codingapi.com/docs/txlcn-lesson02/ 中负载问题的介绍。
*  优化方案：  
    1、支持负载模块的可配化，让用户自行选择是否需要使用负载模式。
    2、当使用我们的负载框架以后，也可以让用户选择可以支持对其扩展。 
    大家有更好的方案，可以回复。

2、序列化问题
* 问题描述：
  序列化问题，也是由于LCN的有状态特点，导致在参与方死掉下次启动的时候补偿的依据。现在优化可以做到将只对发起方的做切面的序列化支持，但是就算是只对发起方的序列化支持依旧还是存在对事务的参数序列化识别的情况，而且还有消耗资源的影响。
* 优化方案：
 目前没有好的优化方案，由于这个异常是在开发时就能发现，所有个人感觉对线上影响不大，但是对消耗性能这点还是很纠结。
 大家有更好的方案，可以回复。

3、连接池优化
* 问题描述：
  由于LCN是有状态，LCN代理的连接在事务通知时才正真的释放，这样对资源的连接占用时间上就会比较长，若业务量大那就会对连接的消耗比较大，会成为对系统的性能瓶颈限制。
* 优化方案：
 将在保留一个专用于LCN模式的连接池，这个连接池需要做到对事务的复用，而非连接的复用，针对对事务的复用上，目前还没有很好的方案，需要讨论。
 大家有更好的方案，可以回复。

4、netty通讯的优化
* 问题描述：
  由于目前netty的通讯上代码层面还是有比较大的优化空间，需要对其性能与代码质量上做进一步的优化。

5、TM去掉的先暂放    

6、 关于代码规范
* 希望大家把代码规范、单元测试规范、提交代码流程规范，社区运营规则规范（主要是针对代码提交的审核与流程）有想法的可以回复一下。     

关于负载问题
![image](https://user-images.githubusercontent.com/5245347/71509066-f3f76800-28c4-11ea-8910-2885255599d5.png)

方案：
[LCN分布式事务-JN20191229.pdf](https://github.com/codingapi/tx-lcn/files/4008087/LCN.-JN20191229.pdf)

**Comment by jiang2992** [comment]
OK

**Comment by liujmcode** [comment]
报名

**Comment by xia10802481** [comment]
报名

**Comment by yizhishang** [comment]
报名

**Comment by our880tom** [comment]
报名

**Comment by michaelyang1988** [comment]
报

**Comment by kmmshmily** [comment]
报名

**Comment by kmmshmily** [comment]
报名

**Comment by daughterkalends** [comment]
收到

**Comment by gitforwangjun** [comment]
报名

**Comment by 1991wangliang** [comment]
希望大家参与到开发中，参与任务讨论与任务认领。感谢 😁
