### ISSUE TITLE
6.0 TC负载与TM选举

### ISSUE THREAD

**Issue by 1991wangliang** [codingapi/tx-lcn#508]
TC模块在于TM通讯的时候可能会存在断开的情况，在关键业务通知环境需要确保通讯的正常。

![image](https://user-images.githubusercontent.com/5245347/86340518-9a169700-bc87-11ea-8924-38e8f1464c2e.png)

**Comment by haichao-hub** [comment]
我对这个比较感兴趣，可以给我实现

**Comment by haichao-hub** [comment]
请问下这个需求除了包含TC与TM通讯，是否还包含事务回滚和删除日志的实现 @1991wangliang

**Comment by 1991wangliang** [comment]
这个任务与#509有点重复，目前#509已经提交了。

**Comment by qiruipeng** [comment]
我试试

**Comment by xlorne** [comment]
该任务与#506 有些雷同，继续维护见 #506
