### ISSUE TITLE
4.0.3.M3 优雅停机问题

### ISSUE THREAD

**Issue by drakelee1221** [codingapi/tx-lcn#53]
txClient客户端，多处线程池ExecutorService和Netty连接，在程序停机时未做destroy处理，导致Spring Boot优雅停机被阻塞，需要做资源释放的位置如下：
SocketManager > [ChannelHandlerContext ctx]  close() 和 channel().eventLoop().shutdownGracefully()
SocketManager > [Executor threadPool]  shutdown()
SocketManager > [ScheduledExecutorService executorService]  shutdown()
NettyServiceImpl > [EventLoopGroup workerGroup] shutdownGracefully()
NettyControlServiceImpl > [Executor threadPool]  shutdown()

**Comment by 1991wangliang** [comment]
线程池关闭优化

**Comment by 1991wangliang** [comment]
感谢，问题已修复. 😀 下个版本发布
