### ISSUE TITLE
Consider defining a bean of type 'com.codingapi.tx.datasource.ILCNTransactionControl' in your configuration.

### ISSUE THREAD

**Issue by xiaobaoger** [codingapi/tx-lcn#58]
版本: 4.0.3.M2
造成原因: 只要在入口方法加入@Import({xx.class}) 就会报错
报错内容：
***************************
APPLICATION FAILED TO START
***************************

Description:

Field transactionControl in com.codingapi.tx.aop.service.impl.TxRunningTransactionServerImpl required a bean of type 'com.codingapi.tx.datasource.ILCNTransactionControl' that could not be found.

Action:

Consider defining a bean of type 'com.codingapi.tx.datasource.ILCNTransactionControl' in your configuration.

**Comment by 1991wangliang** [comment]
应该是包路径扫码有问题，你加上扫码路径'com.codingapi.tx.'
