### ISSUE TITLE
关于LCNDynamicTransactionDataSource、TxTransactionLocal是否是已经在新版删除了

### ISSUE THREAD

**Issue by xiaobaoger** [codingapi/tx-lcn#59]
若已经删除，是因为不支持多数据源还是什么原因？若支持还望在TxTransactionLocal提供remove方法、方便扩展。

**Comment by 1991wangliang** [comment]
LCNDynamicTransactionDataSource 在后面的版本确实已经没有了

**Comment by xiaobaoger** [comment]
是因为本框架目前对多数据源不支持？
