### ISSUE TITLE
@TxTransaction是否支持嵌套

### ISSUE THREAD

**Issue by happyyangyuan** [codingapi/tx-lcn#6]
使用 @TxTransaction ServiceA--> @TxTransaction ServiceB  --> @TxTransaction ServiceC 调用链
实现多种组合的事务

**Comment by happyyangyuan** [comment]
是否可以考虑去掉transactional注解呢？

**Comment by 1991wangliang** [comment]
可以支持调用连接的方式请求。例如 a -b -c -d 。你说的txtransaction是什么意思？你是想让一个个的LCN模块在穿起来？那不就是一次事务吗？你是不是理解错了？

**Comment by 1991wangliang** [comment]
@TxTransaction 仅是分布式事务的一个启动标示。因为LCN不控制事务，只是协调事务。因此也没有考虑将@Transactional的注解合并到该注解下

**Comment by 1991wangliang** [comment]
将在下个版本支持事务7种机制的互相嵌套。

**Comment by happyyangyuan** [comment]
期待“将在下个版本支持事务7种机制的互相嵌套”这个功能。

**Comment by 1991wangliang** [comment]
4.0.2的快照版本已经支持了。预计本月末4.0.2 会发布正式版本。
