### ISSUE TITLE
加了spring-boot-starter-actuator 这个依赖之后lcn连接异常

### ISSUE THREAD

**Issue by sxjsxj1994** [codingapi/tx-lcn#61]
![image](https://user-images.githubusercontent.com/22607591/35836494-7f58df74-0b1b-11e8-988c-cf546a1fd859.png)
![image](https://user-images.githubusercontent.com/22607591/35836501-84fd1b16-0b1b-11e8-95a3-a5cf0220451f.png)
前面是没加的，后面是加了的。前面回滚正常，后面不回滚

**Comment by sxjsxj1994** [comment]
情况描述：springboot版本 1.5.2.RELEASE  
cloud版本 
<spring-cloud.version>Dalston.SR1</spring-cloud.version>

**Comment by 1991wangliang** [comment]
测试并没有发现问题.我是用的最新的源码测试的结果。
操作说明：打包最新的lcn代码。然后运行demo （mybatis下的demo）
https://github.com/codingapi/springcloud-lcn-demo/tree/4.0.3-actuator
