### ISSUE TITLE
txmanage挂掉之后，业务无法正常流转了

### ISSUE THREAD

**Issue by honestAnt** [codingapi/tx-lcn#65]
项目启动阶段，如果txmanage没有启动则服务无法注册到注册中心（dubbo）；
项目运行阶段，如果txmanage宕机，则业务中断；
建议：如果txmanage异常，是否可以执行本地事务？

**Comment by 1991wangliang** [comment]
若宕机了之后继续运行本地事务，那么客户端会导致数据事务不一致的。建议做法是将TxManager做集群化。

**Comment by honestAnt** [comment]
你好，我使用的4.1.0版本的代码；txmanager做集群（两个txmanager服务，nginx分流负载）后发现一个问题；
1：使用dubbo服务的mybatis demo代码运行
2：在第一个服务调用成功后，将txmanager中的一个服务中断（模拟宕机）
3：第二个服务开始调用，运行结束后发现只有一个事务被提交(数据库只有一条数据)
疑惑：按照集群定义来说应该两个都 被提交的，现在只要一个被提交，事务的原子性好像被破坏了？

**Comment by 1991wangliang** [comment]
有没有看到有补偿数据？

**Comment by honestAnt** [comment]
补偿数据在页面有看到，也有记录；但是数据库里面没有生成对应数据；
## 补偿问题追加：还有就是补偿通知的url（tm.compensate.notifyUrl）怎么填呢，文档上面描述说有  "rest api 地址，post json格式)",没有说明具体的api接口；项目默认的地址：“tm.compensate.notifyUrl=http://ip:port/path” 中的path指的是txmanager的访问地址吗,还是指的别的(我配置成/tx/manager/,执行补偿事务方法是会报404错误)
错误信息如下：Compensate Callback Result->{"timestamp":1520236055463,"status":404,"error":"Not Found","message":"No message available","path":"/tx/manager/"}

**Comment by yiniesta** [comment]
这问题怎么就没下文了，一直不知道怎么用补偿

**Comment by mon213** [comment]
补偿机制是怎么补偿的啊？怎么用这个功能？求指教

**Comment by honestAnt** [comment]
集群模式下补偿是个坑，所以作者只是说一下，不建议使用；单机可以考虑一下；具体做法需要添加一个接口然后修改属性文件里面的tm.compensate.notifyUrl指向这个接口（个人摸索的单机模式是可以使用的）；
接口里面直接返回true就行(只是测试验证，正常需要有校验逻辑)，事务补偿就可以使用了；
