### ISSUE TITLE
客户端业务执行失败，记录的事务补偿信息发送给服务器端，但是本地未做记录

### ISSUE THREAD

**Issue by honestAnt** [codingapi/tx-lcn#66]
通过查看源码发现，TxStartTransactionServerImpl里面执行txManagerService.sendCompensateMsg(groupId, time, info,executeConnectionError);时候，本地不做任何记录（saveLocal()里面只做了日志输出），只是将补偿信息发送到服务器端，之后服务器会进行轮询（异常会重复3次）补偿操作；这里面有个问题，如果客户端在发送消息时服务器(txmanager)异常或者txclient网络有问题，会导致补偿失败！

建议(可能待完善)：在saveLocal记录补偿信息(放到redis都行)，之后客户端(txclient)启动检查是否有未执行的补偿信息，有则发送到服务端进行处理；

**Comment by 1991wangliang** [comment]
补偿若失败的话，数据还是存在TxManager下的，可以再次发起补偿的。若将Client端的数据都存在redis下那么Client首先就需要依赖redis，这样会变重也会增加性能消耗的

**Comment by honestAnt** [comment]
问题这样的，可能之前我的描述有些不太清楚;
补偿业务流程  客户端执行业务代码异常，这个时候txclient会做两件事：1 发送补偿数据到txmanager（sendCompensateMsg接口），2  记录服务器反馈的补偿消息结果（打印日志）
猜测：如果在第一步发送补偿数据时网络出问题或者txmanager异常（这个发生概率很低），会导致补偿记录失败（因为这时数据还没有记录，补偿任务里面也没有）

以上只是研究代码发现的，可能也不是太合理，后续希望能持续改善和交流；

**Comment by 1991wangliang** [comment]
但是补偿成功的条件是执行到了最后一步，而且最后一步也是关系到数据库事务是提交还是回滚的地方。因此这里的网络异常若存在问题也会导致最终的补偿失败的，理论上之关心最后Tx-manager通知的情况。

**Comment by honestAnt** [comment]
了解；目前所有的补充记录及处理操作都是在服务端做的（真正事务执行在客户端），所以是否可以在客户端做个备份（首问的解决方案），这样虽然客户端的操作"重"了，但是事务补偿这块机制的风险就降低了很多。
