### ISSUE TITLE
事务补偿的时序图麻烦给个，谢谢

### ISSUE THREAD

**Issue by alanjing** [codingapi/tx-lcn#67]
事务补偿的时序图麻烦给个，这个过程还不是很清楚，谢谢

**Comment by klboke** [comment]
https://github.com/codingapi/tx-lcn/wiki/LCN%E5%8E%9F%E7%90%86 项目wiki说的很清楚啊

**Comment by alanjing** [comment]
wiki上面只有正常和异常执行回滚的，没有补偿情景的时序图

**Comment by honestAnt** [comment]
流程：客户端业务执行失败->通知txmanager保存事务信息（http）->发送校验通知（业务方提供api接口）->success情况下执行自动补偿逻辑->通知客户端执行事务补偿（netty；不成功会重复3次）->服务器发送 事务补偿执行结果通知 请求(http)
