### ISSUE TITLE
txmanager负载情况下，ModelInfoManager获取在线模块（客户端对象）异常

### ISSUE THREAD

**Issue by honestAnt** [codingapi/tx-lcn#68]
通过代码调试发现，客户端连接对象存储是放在内存中的(private List<ModelInfo> modelInfos = new CopyOnWriteArrayList<ModelInfo>();),如果是负载情况下，客户端对象存储都是基于内存的，无法做到共享，所以补偿是会出现异常，其他问题有待发现

建议：对象存储在redis中；

**Comment by honestAnt** [comment]
我这边尝试把channel放到redis，发现取出来异常（channel未序列号，且封装的东西太多）；
是否可以用别的手段来搞？

**Comment by 1991wangliang** [comment]
我想起来了，在线的模块其实不需要共享的。当在线模块发给送Tx-manager请求的时候，Tx-manager是会将Tx-manager的地址信息存放在redis下的。若该调用链不在一个Tx-manager下，他会去寻找Tx-manager服务的。相当于是共享了Tx-manager，这样就不需要共享tx-client的模块信息了啊

**Comment by honestAnt** [comment]
大哥，你这和客户端通信的用的是SocketManager啊；这玩意你不做负载你怎么玩啊
