### ISSUE TITLE
txManager负载均衡通过服务发现方式如何配置

### ISSUE THREAD

**Issue by 852675742** [codingapi/tx-lcn#70]

**Comment by 690713748** [comment]
@Service
public class TxManagerTxUrlServiceImpl implements TxManagerTxUrlService{
    @Autowired
    private LoadBalancerClient loadBalancerClient;
    @Value("${tm.manager.serviceId:tx-manager}")
    private String serviceId;

    @Override
    public String getTxUrl() {
        ServiceInstance serviceInstance = loadBalancerClient.choose(serviceId);
        String url = "http://"+ serviceInstance.getHost() + ":" + serviceInstance.getPort() + "/tx/manager/";
        System.out.println("load tm.manager.url:" + url);
        return url;
    }
}
我这样配置，希望对您有帮助

**Comment by 690713748** [comment]
你好，我这样配置，你可以参考一下，如有错误之处，请指出，希望对你有帮助，谢谢。
@Service
public class TxManagerTxUrlServiceImpl implements TxManagerTxUrlService{


    @Autowired
    private LoadBalancerClient loadBalancerClient;
    @Value("${tm.manager.serviceId:tx-manager}")
    private String serviceId;

    @Override
    public String getTxUrl() {
        ServiceInstance serviceInstance = loadBalancerClient.choose(serviceId);
        String url = "http://"+ serviceInstance.getHost() + ":" + serviceInstance.getPort() + "/tx/manager/";
        System.out.println("load tm.manager.url:" + url);
        return url;
    }
}

**Comment by honestAnt** [comment]
这块代码不需要动；用nginx或者apache代理一下就行

**Comment by ouyang1203** [comment]
按照上面那个配置了集群，但是在之前使用的那个tx-manager服务down掉之后不会切到另外一个tx-manager服务上面，是有什么没配全么？
