### ISSUE TITLE
关于spring cloud的回滚原理

### ISSUE THREAD

**Issue by a252937166** [codingapi/tx-lcn#72]
`spring cloud`的服务是`http`的方式调用的，本地应该没法控制被调用方的连接池的。
架设有这么一个情景：
那么如果A服务器调用B服务器的服务，B服务成功，再调用C服务器的服务，C服务失败。
那么A服务器是因为`TX`改写连接池代理，可以实现回滚。但是B服务如何回滚呢？

**Comment by 1991wangliang** [comment]
你说的这样的情况 只要有本地事务就可以啊 a->b->c ，调用c的时候失败。那么c会异常的。异常传递到b和a时，本地事务也会回滚了啊

**Comment by a252937166** [comment]
刚才看了你的demo，懂了。
那么这样的话，如果服务方本身是单表操作，并没有加事务，那就没法处理了吧。

**Comment by a252937166** [comment]
我的意思是，b已经成功了，b作为一个`http`的请求，是短连接，a请求b之后，正常情况下和b的连接已经中断了，c的异常返回给a没有问题。关键c的异常是如何返回给b的呢，如果a服务器多线程调用b和c的服务，b<-a->c，这种情况，你这边是如何设计保证同步的呢？

**Comment by rench** [comment]
@a252937166  短连接不是说建立连接发送了消息就关闭了，而是要接受返回的消息后在关闭。a->b->c，如果c不返回,a、b都是被挂着的（同步方式下）

**Comment by a252937166** [comment]
@rench 就算b挂着，也是在controller层返回之后啊，这时service层的事务应该已经结束了啊，这个框架是怎么控制到`http`方法被调用方的业务的呢？

**Comment by yunfei90** [comment]
@a252937166  看框架的原理，返回之后并没有真正提交。 而是所有业务处理完后由事务管理器发通知让参与事务的各方再提交的。 @rench  不知道我理解的对不对。

**Comment by war3sxkcs** [comment]
长连接，假提交的啊。是这样理解的嘛，哈哈
