### ISSUE TITLE
dubbo TransactionFilter

### ISSUE THREAD

**Issue by laoztb** [codingapi/tx-lcn#75]
4.10版本
dubbo 服务 TransactionFilter   TxTransactionLocal.current();为null   无法创建groupId
好奇怪

**Comment by liliang8858** [comment]
同样问题。。。求问

**Comment by whthomas** [comment]
看了下源码，spring项目启动的时候需要扫描 package `com.codingapi.tx`

**Comment by xiaobei-ihmhny** [comment]
对呀，同求，groupId为null，事务也没有回滚
