### ISSUE TITLE
最新4.1.0 Demo搭建疑问

### ISSUE THREAD

**Issue by tandingbo** [codingapi/tx-lcn#76]
不知是否支持一下版本
<spring-cloud.version>Finchley.M8</spring-cloud.version>
<spring-boot.version>2.0.1.RELEASE</spring-boot.version>
我按照提供的Demo来做，应用不能正常启动：
Initialization of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'transactionAspect': Unsatisfied dependency expressed through field 'txManagerInterceptor';
nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'txManagerInterceptor': 
Unsatisfied dependency expressed through field 'aspectBeforeService';
nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'aspectBeforeServiceImpl': Unsatisfied dependency expressed through field 'transactionServerFactoryService'; 
nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'transactionServerFactoryServiceImpl': 
Unsatisfied dependency expressed through field 'txStartTransactionServer'; 
nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'txStartTransactionServer': Unsatisfied dependency expressed through field 'txManagerService'; 
nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException:
Error creating bean with name 'MQTxManagerServiceImpl': Unsatisfied dependency expressed through field 'modelNameService';
nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException:
Error creating bean with name 'modelNameServiceImpl': Unsatisfied dependency expressed through field 'serverListener'; 
nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverListener':
Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.codingapi.tx.springcloud.listener.ServerListener] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]

**Comment by 1991wangliang** [comment]
现在测试都是基于1.5.x 的springboot版本。2.0以上应该不兼容。我们会考虑兼容的。

**Comment by tandingbo** [comment]
非常感谢你的回复，我已调整版本在学习中，持续关注中

**Comment by mogoboss** [comment]
我也在尝试集成LCN4.1.0，发现无法在以下版本中应用，一般为报以下错误：
org.springframework.beans.factory.UnsatisfiedDependencyException
org.springframework.beans.BeanInstantiationException
以上两个主错误引发了一系列的错误
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.1.RELEASE</version>
        <relativePath/> 
    </parent>
