### ISSUE TITLE
对于事务补偿机制中的疑问

### ISSUE THREAD

**Issue by linpingchuan** [codingapi/tx-lcn#8]
- 看你的文档中，你不是使用2PC,3PC等来保证事务的一致性，那么你是不是还是需要至少进行两次网络往返？

- 有一个问题就是，在Spring Cloud中，有一个业务B，需要调用B1,B2和B3等三个业务，B1,B2和B3都已经成功的执行了事务之后，通知到TxManager，然后TxManager进行通知TxClient进行数据库提交。在此时，B1和B2能够成功的通知到了，但是B3此时出现了网络震荡，始终无法到达，** 阻塞 ** 在网络途中，那么根据你的超时机制，B1和B2被自动回滚了。那么这样的话，B3还未到超时时间，你的B3被自动提交了。是不是意味着出现了数据不一样的情况了？

我认为，不应该存在这种超时的机制，并且B3如果宕机了，再次重启，你是如何保障该业务数据重新提交到数据库呢？

 这是我的<a href="mailto:paul_lin@foxmail.com">联系方式</a>。
可以向我发邮件进行沟通
期待您的回复. :smile:

**Comment by 1991wangliang** [comment]
在关闭事务组的时候，存在产生补偿的情况。所谓的补偿是指在通知模块时发现有没有响应的模块，此时TxManager就会识别为补偿然后通知给发起方。发起方会标示本次事务提交给TxManager，然后在进行补偿处理。

**Comment by linpingchuan** [comment]
那如果在通知给发起方的时候，发起方宕机了，这个时候你会一直无限重试一下吗？

**Comment by 1991wangliang** [comment]
这里还没有那么做，主要是在找一个平衡点。若这样做意味着在创建事务组的时候就需要将切面信息传递给TxManager，这样的话数据量就比较大。请求补偿不是高频操作，为此加了这个考虑就有点重了。现在的做法是比较聪明的做法，在spring机制下事务是会开启自动提交的。在执行关闭事务组的方法的时候，说明事务方法已经执行完了，此时就算挂了，数据库的时候还是会继续执行完的。

**Comment by linpingchuan** [comment]
> 此时就算挂了，数据库的事务还是会继续执行完的。
这句话，我有点不太理解。你的事务是自动提交的，就是说不发生异常的话，那么他是会自动提交。那现在是机器直接无响应了（宕机）。那他还会自动提交的吗？这个有点困惑。

然后我这边想到的一个比较好的方案是说，事务会有个SavePoint。将其这个事务快照发送到TxManager，如果机器挂掉了，应该还是可以继续提交了。

另外，宕机的情况很少发生。但是作为Spring Cloud的第三方补充，我们应该还是要能够充分解决这个问题。而不是把这个最关键的问题抛给用户进行解决。:smile:

**Comment by 1991wangliang** [comment]
SavePoint 的方式是不可行的，最早在设计的时候就考虑过。savePoint在断开连接以后就失效了。

**Comment by 1991wangliang** [comment]
```
    @Around("execution(* com.example.demo.service.impl.*Impl.*(..))")
    public Object around(ProceedingJoinPoint point)throws Throwable{
        try {
           
            Object obj = point.proceed();
            
            return obj;
            
        }catch (Exception e){
            throw e;
        }finally {
            //关闭事务组操作
            
            System.out.println("挂掉服务");
            
            System.exit(0);
        }
    }

```

**Comment by linpingchuan** [comment]
哦。那我们如果拿到那个局部事务ID,宕机后进行重启，再来进行提交也是不可以的是吗

**Comment by 1991wangliang** [comment]
最保险的做法是在开启事务的时候，将事务的切面信息提交给TxManager。然后后面就算挂了，也可以通过TxManager找到对应的服务，然后发送指令让其补偿。但是这样的做法会导致发起请求的数据量过大..记录本地的方式，3.0是那样做的，但是觉得也不是很好。本地每次读写也是效率，而且还有设计一个存储的方式

**Comment by 1991wangliang** [comment]
其实现在方式就，我分析过很多方案以后的上策了， 😀   可以做到事务的一致性，也不影响性能。你是不是对补偿决策机制觉得有问题？

**Comment by 1991wangliang** [comment]
LCN,对于模块区分为：发起方，参与方。发起方的Connection连接完全是用的本地的连接，不是LCN的代理连接。仅是参与方的连接是代理的连接而已。在4.0.2的版本下也做了优化，将使用功能上做到了与本地事务一直的效果了。

**Comment by linpingchuan** [comment]
还有你的补偿，看一下我的理解是否正确。
举例来说，有个业务B,然后B1这个业务主机，是对其进行删除操作。B2这个主机，是对其进行增加操作。
1.
B1进行完整的操作。等待TxManager通知
B2在等待TxManager通知的时候。

2.
TxManager确定全部通过提交。
B1成功提交了。
B2因为网络震荡或者主机无法提交，此时会自动提交吗？

另外一种情况就是，B1等待通知，B2出现了异常了。这个时候TxManager会准备回滚操作。
此时B1因为网络震荡或者主机宕机。他是会自动提交的，对吧。

后面B1主机重启回来之后，TxManager会重新发送sql命令，让B1进行回滚操作吗？

**Comment by linpingchuan** [comment]
你的模块应该不是发起方，参与方。你应该还有个协调方(TxManager)。

我这边确实对于你的事务补偿机制存在着很大的困惑。 :laughing:

**Comment by linpingchuan** [comment]
另外对于那个JTA，我这边有一个很好的[资料](https://www.ibm.com/developerworks/cn/java/j-lo-jta/index.html)。但是还是有点稍微看不懂。

我在这篇文章中，看到那个UML图中，觉得有个值得注意的地方就是他的Xid。感觉这个可能能解决我上面的那些疑惑。

**Comment by 1991wangliang** [comment]
B2因为网络震荡或者主机无法提交，此时会自动提交吗？
这里就比较麻烦了，存在两种情况：
1.发起方在执行关闭事务的时候，参与方的自动提交请求还没有执行。
当此时会记录补偿，并删除redis的补偿日志记录，然后通过补偿决策机制进行补偿，那么过会可能自动补偿机制执行了，当请求发现没有了补偿数据，那么他会执行回滚的。因此这样的情况完全靠补偿就可以了。
2.发起方在执行关闭事务的时候，参与方的自动提交请求已经执行。
当此时也会记录补偿数据，此时会判断补偿是否存在需要通知的模块，若发现没有需要通知的模块。补偿会自动删除掉。不做处理，那么这样的情况下也没有问题的。

后面B1主机重启回来之后，TxManager会重新发送sql命令，让B1进行回滚操作吗？

自动补偿机制，尽在发现补偿提交的时候会执行提交事务，其他状态下都会回滚事务。

**Comment by 1991wangliang** [comment]
JTA的方式我也研究过，但是他最大的弊端是在于性能上。以及数据库的兼容性上。但是可以利用LCN的思路用JTA的技术路线实现一遍。

**Comment by linpingchuan** [comment]
在于性能？
能否详细说明一下

**Comment by 1991wangliang** [comment]
JTA是真正的两阶段请求的，可以理解一步db操作拆分了两步。
站在分布式事务的角度，主要考虑的两个东西：低依赖与性能。
分布式事务的业务方法未必是所有的业务都需要的，因此若都采用两阶段本身对项目性能有极大的影响。其次就是与本地的业务低耦合性上。

**Comment by linpingchuan** [comment]
不对。分布式事务，更重要考虑的是数据的一致性。不然你的性能再好，数据不正确。那你的系统就没有准确性而言了。

你是在哪里看到JTA是二段式的 :laughing:

**Comment by 1991wangliang** [comment]
本来不就是两阶段吗？

**Comment by linpingchuan** [comment]
我这那篇文章没有看到这个

**Comment by 1991wangliang** [comment]
https://github.com/1991wangliang/xa-transaction-demo  基于 atomikos 的两阶段demo

**Comment by ninyjun** [comment]
整个项目想法很好，在目前微服务流行的架构模式下，事务问题确实是个头疼的问题，业务调用实际情况会比这个复杂许多，解决最终事务一致问题基本需要和具体的业务相关联，这种模式只能作为一个简单补充，单靠这个去保证事务最终一致是不现实的。

**Comment by sanwancoder** [comment]
> 在关闭事务组的时候，存在产生补偿的情况。所谓的补偿是指在通知模块时发现有没有响应的模块，此时TxManager就会识别为补偿然后通知给发起方。发起方会标示本次事务提交给TxManager，然后在进行补偿处理。

事务补偿这一块可以搞个视频讲一讲哈
