### ISSUE TITLE
事务发起方疑问

### ISSUE THREAD

**Issue by gitveio** [codingapi/tx-lcn#83]
作者你好，比如有三个接口A、B、C，A调用B，B调用C，但是对外提供的接口是A和B，用户可能调用A接口，也可能直接调用B接口，那A添加isStart=true属性，B是不是也要添加还是怎么样

**Comment by aixiaotan** [comment]
不需要




| |
裴洪伟
邮箱：ziniang5211@163.com
|

签名由 网易邮箱大师 定制

在2018年04月25日 17:08，ww 写道：

作者你好，比如有三个接口A、B、C，A调用B，B调用C，但是对外提供的接口是A和B，用户可能调用A接口，也可能直接调用B接口，那A添加isStart=true属性，B是不是也要添加还是怎么样
