### ISSUE TITLE
关于在线模块永远只有一个的问题

### ISSUE THREAD

**Issue by OnceCrazyer** [codingapi/tx-lcn#88]
在测试中，发现启动多个微服务，首页-当前连接数 的数量是正常的，但是在线模块中的数据永远只有第一个启动的服务。经阅读源代码后发现，在ModelInfoManager类下的addModelInfo方法中有个判断方法存在问题，
if (minfo.getIpAddress().equalsIgnoreCase(modelInfo.getIpAddress())) {
                return;
            }
这块代码，当都在一个机器上启动时，会存在后面的服务都不会加到list中（当然正常环境中微服务应该都是部署在不同的机器上的）。
请问下，这个modelInfos list 中的模块节点，是否会用到当在事务回滚或者事务补偿时把事务在同一个微服务节点上执行？还是只是用来进行数据显示的？

**Comment by dmcslt** [comment]
为啥我一个模块没有，

**Comment by fsraymond** [comment]
你是否dubbo的？

根源貌似是这里：
com.codingapi.tx.dubbo.service.impl.ModelNameServiceImpl.providerConfig()

        Map<String, ProviderConfig> beans =   applicationContext.getBeansOfType(ProviderConfig.class);
        ProviderConfig providerConfig = null;
        if(beans!=null){
            String defaultKey = "default";
            for(String key:beans.keySet()){
                defaultKey = key;
            }

            providerConfig =  beans.get(defaultKey);
        }
        return providerConfig;
    }

这里providerConfig无法读取自定义的dubbo配置文件
就算官方dubbo demo也是

**Comment by fsraymond** [comment]
https://github.com/codingapi/tx-lcn/issues/149
我在这个问题里面自己改代码解决了本地多模块在线
