### ISSUE TITLE
整合spring cloud 时提示检测tx.properties文件

### ISSUE THREAD

**Issue by AaronChenlin** [codingapi/tx-lcn#93]
你好，我通过lcn的spring cloud demo在已有项目中尝试加入lcn的支持，然后启动项目的时候遇到了这个提示，我不知道这个问题出在哪里，所以我希望得到你的帮组

**Comment by tanaduus** [comment]
你好，我也遇到了，请问你怎么解决的？

**Comment by tanaduus** [comment]
找到原因了。。。

**Comment by tanaduus** [comment]
找到原因了。。。例子service下面有一个TxManagerTxUrlServiceImpl。这个类来读取tm.manager.url的。如果没有这个类。就会默认的去读取一个叫tx.propertites的文件(并没有这个文件)。

**Comment by 84yy** [comment]
3楼的方法完美解决
